export const COLORS = {
  primary: '#C41230',
  dark: '#1A1A1A',
  sectionNews: '#0D3B6E',
  sectionSports: '#1B5E20',
  sectionOpinion: '#4A148C',
  sectionLocalPolitics: '#92400E',
  gray: '#666666',
  lightGray: '#F7F7F7',
  border: '#E0E0E0',
};

export const SECTION_COLORS = {
  news: COLORS.sectionNews,
  sports: COLORS.sectionSports,
  opinion: COLORS.sectionOpinion,
  'local-politics': COLORS.sectionLocalPolitics,
};

export const SECTION_LABELS = {
  news: 'News',
  sports: 'Sports',
  opinion: 'Opinion',
  'local-politics': 'Local Politics',
};

export const SECTION_TAGLINES = {
  news: 'Local government, community, education, and business coverage from across the Fox Valley.',
  sports: 'High school, youth, and recreational sports from Kane and Kendall counties.',
  opinion: 'Editorials, letters to the editor, and commentary from Tribune staff and the community.',
  'local-politics': 'Elections, city councils, school boards, and the people who shape local government.',
};

export const PIANO_CONFIG = {
  AID: 'QiNgMM49pu',
  OFFER_ID: 'OFSKQS2JDQIS',
  SUBSCRIBER_RESOURCE_ID: null,
};

export const ARTICLES = [
  // ── NEWS ──────────────────────────────────────────────────────────────────
  {
    id: 1,
    slug: 'county-board-approves-road-repair-budget',
    section: 'news',
    title: 'County Board Approves $2.3M Road Repair Budget for 2026',
    byline: 'Tribune Staff',
    date: 'April 28, 2026',
    category: 'Government',
    excerpt: 'The Kane County Board voted 18-3 Tuesday to approve a $2.3 million road repair budget for the 2026 fiscal year, prioritizing 14 miles of deteriorating county roads.',
    body: [
      'The Kane County Board voted 18-3 Tuesday to approve a $2.3 million road repair budget for the 2026 fiscal year, prioritizing 14 miles of deteriorating county roads that officials say have reached the end of their useful life.',
      'The measure allocates $1.4 million for resurfacing projects in the eastern district and $900,000 for drainage improvements on Route 47 north of Huntley. Work is expected to begin in late May and wrap up before first frost.',
      '"These roads have been on our radar for five years," said County Engineer Patricia Hollis. "We\'ve done everything we can to extend their life with patch repairs, but we\'ve reached the point where we need to invest properly."',
      'The funding comes from a combination of state transportation grants and county motor fuel tax revenues.',
      'Three board members voted against the measure, citing concerns about the bidding process and calling for more competitive contract solicitation.',
    ],
    tags: ['news', 'government', 'politics', 'infrastructure'],
    locked: true,
    featured: true,
  },
  {
    id: 2,
    slug: 'new-grocery-store-downtown-geneva',
    section: 'news',
    title: 'New Full-Service Grocery Store Planned for Downtown Geneva',
    byline: 'Tribune Staff',
    date: 'April 27, 2026',
    category: 'Business',
    excerpt: 'A Chicago-based grocery chain announced plans to open a 28,000-square-foot store in the former Sears building on State Street.',
    body: [
      'A Chicago-based grocery chain announced plans Monday to open a 28,000-square-foot store in the former Sears building on State Street, ending a three-year search by city planners for an anchor tenant.',
      'Fresh Thyme Market, which operates 24 stores in the Midwest, signed a 15-year lease and expects to open by March 2027 pending city approvals.',
      '"This is exactly the kind of tenant we\'ve been working to attract," said Geneva City Manager Rob Godskesen.',
      'The store will employ approximately 85 full- and part-time workers and generate an estimated $180,000 in annual sales tax revenue for the city.',
    ],
    tags: ['news', 'business-and-finance', 'community'],
    locked: false,
    featured: false,
  },
  {
    id: 3,
    slug: 'school-district-teacher-shortage',
    section: 'news',
    title: 'School District Faces Growing Teacher Shortage Ahead of Fall',
    byline: 'Education Reporter',
    date: 'April 26, 2026',
    category: 'Education',
    excerpt: 'With 34 open teaching positions and hiring season underway, District 303 officials are weighing emergency certification programs and increased pay for hard-to-fill roles.',
    body: [
      'With 34 open teaching positions and the prime hiring season half over, School District 303 is facing its most acute staffing shortage in more than a decade.',
      'The vacancies span nearly every subject area but are most concentrated in special education, high school math, and elementary bilingual classrooms.',
      '"We\'re competing with every district in the region for the same pool of candidates," said Human Resources Director Tanya Ostrander.',
      'The board voted to authorize emergency hiring measures including signing bonuses of up to $5,000 for high-need positions.',
      'Officials also said they are exploring a grow-your-own pipeline program that would offer tuition assistance to paraprofessionals already working in the district.',
    ],
    tags: ['news', 'education', 'family-and-parenting'],
    locked: true,
    featured: false,
  },
  {
    id: 4,
    slug: 'water-main-break-route-31',
    section: 'news',
    title: 'Water Main Break Closes Lanes on Route 31 Near Elgin',
    byline: 'Tribune Staff',
    date: 'April 25, 2026',
    category: 'Local',
    excerpt: 'A 12-inch water main ruptured Tuesday morning, closing two northbound lanes and cutting service to approximately 800 customers.',
    body: [
      'A 12-inch water main ruptured early Tuesday morning near the intersection of Route 31 and Bowes Road, closing two northbound lanes and cutting water service to approximately 800 customers.',
      'Crews from the Fox Valley Water Authority responded at 4:42 a.m. and worked through the afternoon to isolate the break and restore pressure.',
      'Service was fully restored by 6:30 p.m. Northbound lanes on Route 31 remained partially closed through Wednesday morning.',
      'The main, installed in 1987, had been flagged in the authority\'s infrastructure assessment as nearing the end of its expected service life.',
    ],
    tags: ['news', 'infrastructure', 'local-government'],
    locked: false,
    featured: false,
  },
  {
    id: 11,
    slug: 'aurora-community-center-east-side',
    section: 'news',
    title: 'Aurora Breaks Ground on $4.1M East Side Community Center',
    byline: 'Tribune Staff',
    date: 'April 24, 2026',
    category: 'Community',
    excerpt: 'City and state officials gathered Tuesday for a groundbreaking ceremony on a long-awaited community center that will serve an estimated 1,200 residents per week.',
    body: [
      'City and state officials gathered Tuesday morning on a vacant lot at the corner of New York and Hill Avenue for the groundbreaking of a $4.1 million community center that will serve Aurora\'s east side.',
      'The 18,000-square-foot facility will include a gym, after-school tutoring rooms, senior programming space, and a commercial kitchen for community food programs.',
      '"This neighborhood has waited a long time for this investment," said Mayor Richard Irvin. "It\'s a down payment on what this community deserves."',
      'Funding comes from a mix of federal Community Development Block Grant dollars, state capital appropriations secured by Rep. Maura Hirschauer, and a $600,000 private donation from the Fox Valley Community Foundation.',
      'The center is expected to open by spring 2027. A nonprofit operator has not yet been selected; the city expects to issue an RFP this summer.',
    ],
    tags: ['news', 'community', 'government'],
    locked: true,
    featured: false,
  },
  {
    id: 12,
    slug: 'fox-valley-hospital-expansion',
    section: 'news',
    title: 'Fox Valley Regional Hospital Expansion Will Add 80 Beds, New ER Wing',
    byline: 'Health Reporter',
    date: 'April 23, 2026',
    category: 'Health',
    excerpt: 'The $112 million expansion project will nearly double the emergency department\'s capacity and add a new cardiac care unit by late 2028.',
    body: [
      'Fox Valley Regional Medical Center announced Tuesday a $112 million expansion that will add 80 inpatient beds and nearly double the capacity of its emergency department, addressing wait times that have grown steadily since 2022.',
      'The project, funded through a combination of hospital revenue bonds and a state health infrastructure grant, will also include a dedicated cardiac care unit and an expanded surgical suite.',
      '"The Fox Valley\'s population has grown significantly, and our facility needs to grow with it," said CEO Dr. Linda Castellano. "This expansion is essential to maintaining the standard of care our community expects."',
      'Construction is expected to begin in late summer. The expanded ER wing is projected to open in phases, with the first phase operational by early 2028.',
      'The hospital currently sees approximately 65,000 emergency visits per year — up from 44,000 a decade ago. The new ER will be designed to handle up to 90,000 visits annually.',
    ],
    tags: ['news', 'health'],
    locked: true,
    featured: false,
  },
  {
    id: 13,
    slug: 'batavia-farmers-market-returns',
    section: 'news',
    title: "Batavia Farmer's Market Returns May 10 with Record 60 Vendors",
    byline: 'Tribune Staff',
    date: 'April 22, 2026',
    category: 'Community',
    excerpt: "This year's market will feature a record 60 vendors, a new prepared-food tent, and extended Saturday hours through October.",
    body: [
      "The Batavia Farmer's Market opens for its 28th season on Saturday, May 10, with a record 60 vendors — up from 47 last year — and several new features organizers say reflect growing demand.",
      'New this year: a prepared-food tent with eight rotating food vendors, a kids\' activity area sponsored by the Batavia Park District, and extended hours on Saturdays from 7 a.m. to 1 p.m.',
      '"We had a waiting list of vendors for the first time in our history," said Market Director Angela Smits. "The community\'s appetite for local food has never been stronger."',
      "The market runs Saturdays through October 25 in the city's downtown district on Wilson Street. A Wednesday evening market launches June 4 and runs through August.",
    ],
    tags: ['news', 'food-and-drink', 'community'],
    locked: false,
    featured: false,
  },

  // ── SPORTS ────────────────────────────────────────────────────────────────
  {
    id: 5,
    slug: 'batavia-bulldogs-regional-championship',
    section: 'sports',
    title: 'Batavia Bulldogs Capture Regional Title in Overtime Thriller',
    byline: 'Tribune Sports',
    date: 'April 28, 2026',
    category: 'High School Soccer',
    excerpt: 'Senior midfielder Connor Walsh scored in the 94th minute to lift Batavia past St. Charles East 2-1 in a regional boys soccer final.',
    body: [
      'Senior midfielder Connor Walsh scored in the 94th minute to lift the Batavia Bulldogs past St. Charles East 2-1 in a regional boys soccer final Saturday.',
      'Walsh collected a through ball from sophomore Mateo Hernandez and beat the keeper low to the left post.',
      '"I was just trying to stay patient and wait for my moment," Walsh said afterward.',
      'The Bulldogs, now 16-4-2, advance to the sectional semifinals Wednesday against Wheaton Warrenville South.',
      'St. Charles East had taken the lead at 62 minutes on a free kick from Damian Torres before Batavia equalized on a penalty by junior Kyle Peterson at 71 minutes.',
    ],
    tags: ['sports', 'soccer', 'high-school-sports'],
    locked: true,
    featured: true,
  },
  {
    id: 6,
    slug: 'st-charles-north-wrestler-state-title',
    section: 'sports',
    title: 'St. Charles North Senior Wins State Wrestling Title at 170 Pounds',
    byline: 'Tribune Sports',
    date: 'April 26, 2026',
    category: 'High School Wrestling',
    excerpt: 'Marcus Webb pinned his opponent in 1:47 of the championship match to give St. Charles North its first individual state wrestling title since 2019.',
    body: [
      'Marcus Webb pinned his Springfield Southeast opponent in 1:47 of the championship match Saturday to give St. Charles North its first individual state title in wrestling since 2019.',
      'Webb, a three-time state qualifier who finished third a year ago, was dominant throughout the tournament, allowing just five points across five matches.',
      '"This is what I\'ve worked for since I was a freshman," said Webb, who finished the season 41-1.',
      'Webb committed to the University of Illinois in February.',
    ],
    tags: ['sports', 'wrestling', 'high-school-sports'],
    locked: true,
    featured: false,
  },
  {
    id: 7,
    slug: 'youth-soccer-league-expansion',
    section: 'sports',
    title: 'Fox Valley Youth Soccer League Expanding to Three New Communities',
    byline: 'Tribune Staff',
    date: 'April 24, 2026',
    category: 'Youth Sports',
    excerpt: 'The Fox Valley Youth Soccer League will add divisions in Carpentersville, Burlington, and Sleepy Hollow starting with the fall 2026 season.',
    body: [
      'The Fox Valley Youth Soccer League announced Thursday it will expand into three new communities — Carpentersville, Burlington, and Sleepy Hollow — beginning with the fall 2026 season.',
      'The expansion adds approximately 340 players and nine new teams to a league that currently serves more than 2,400 youth athletes across 18 communities.',
      '"The demand in these communities has been there for years," said league director Angela Moreno.',
      'Registration for fall leagues opens May 15 at foxvalleysoccer.org.',
    ],
    tags: ['sports', 'soccer', 'family-and-parenting', 'youth-sports'],
    locked: false,
    featured: false,
  },
  {
    id: 14,
    slug: 'olivia-park-northwestern-swim',
    section: 'sports',
    title: 'Geneva Senior Olivia Park Signs with Northwestern Swimming',
    byline: 'Tribune Sports',
    date: 'April 25, 2026',
    category: 'High School Swimming',
    excerpt: 'The four-time state qualifier and two-time individual champion will join the Wildcats\' program in the fall, the first Geneva swimmer to commit to a Big Ten program since 2019.',
    body: [
      'Geneva High School senior Olivia Park signed her National Letter of Intent to swim at Northwestern University on Wednesday, becoming the first Geneva swimmer to commit to a Big Ten program in seven years.',
      'Park, a four-time state qualifier and two-time individual state champion in the 200 freestyle, chose Northwestern over offers from Michigan State, Wisconsin, and Indiana.',
      '"Northwestern felt like home from my first visit," Park said at a signing ceremony attended by teammates and coaches. "The academics are unbeatable and the program is on the rise."',
      'She finished this season with a personal-best 1:47.31 in the 200 freestyle — the fourth-fastest time in Illinois this year.',
      'Geneva head coach Dana Rekowski called Park "the most complete swimmer we\'ve developed in 15 years of this program." She will graduate in June and join Northwestern\'s roster in September.',
    ],
    tags: ['sports', 'swimming', 'high-school-sports'],
    locked: true,
    featured: false,
  },
  {
    id: 15,
    slug: 'fox-valley-marathon-returns',
    section: 'sports',
    title: 'Fox Valley Marathon Returns After Three-Year Hiatus',
    byline: 'Tribune Sports',
    date: 'April 23, 2026',
    category: 'Road Racing',
    excerpt: 'Registration is open for the October 5 race, which will follow a redesigned course through Geneva, Batavia, and St. Charles.',
    body: [
      'The Fox Valley Marathon is back. Race organizers announced Wednesday that the event — which last ran in 2022 before a three-year pause — will return on October 5 with a redesigned course and a new title sponsor.',
      'The 26.2-mile course winds through Geneva, Batavia, and St. Charles along the Fox River Trail, with the finish line at the Pottawatomie Park amphitheater in St. Charles.',
      'Registration is open at foxvalleymarathon.com. Early-bird pricing is $95 for the full marathon and $65 for the half marathon through June 1.',
      '"We heard from runners every year asking when we were coming back," said race director Kevin Hollenbeck. "The community support for this event has always been exceptional."',
    ],
    tags: ['sports', 'running', 'road-racing'],
    locked: false,
    featured: false,
  },
  {
    id: 16,
    slug: 'spring-baseball-preview',
    section: 'sports',
    title: 'Spring Baseball Preview: Five Fox Valley Teams to Watch',
    byline: 'Tribune Sports',
    date: 'April 21, 2026',
    category: 'High School Baseball',
    excerpt: 'Batavia, St. Charles East, Geneva, Kaneland, and Oswego East enter the postseason with legitimate sectional championship aspirations.',
    body: [
      'With sectional play approaching, five Fox Valley programs have emerged as legitimate contenders for deep playoff runs. Here\'s a look at each.',
      'Batavia (18-3) leads the Upstate Eight with a rotation anchored by junior right-hander Drew Patterson, who carries a 0.91 ERA and has struck out 87 batters in 54 innings.',
      'St. Charles East (16-4) is powered by one of the conference\'s best lineups, averaging 7.4 runs per game behind senior centerfielder Jake Morales (.418 average, 6 home runs).',
      'Geneva (14-6) is the most balanced of the contenders — no single standout but deep pitching and a defense that has committed just nine errors all season.',
      'Kaneland (13-7) and Oswego East (13-6) both feature elite arms and the kind of veteran experience that tends to matter in elimination games.',
    ],
    tags: ['sports', 'baseball', 'high-school-sports'],
    locked: true,
    featured: false,
  },

  // ── OPINION ───────────────────────────────────────────────────────────────
  {
    id: 8,
    slug: 'editorial-infrastructure-investment',
    section: 'opinion',
    title: 'Editorial: The Time to Fix Our Roads Is Now',
    byline: 'Tribune Editorial Board',
    date: 'April 28, 2026',
    category: 'Editorial',
    excerpt: "The county board's road repair vote is welcome — but it's a down payment on years of deferred maintenance.",
    body: [
      "Tuesday's county board vote approving $2.3 million for road repairs is welcome news for drivers who have navigated the same crumbling county roads for the better part of a decade. But it's a down payment, not a solution.",
      "Kane County's infrastructure maintenance backlog now exceeds $47 million by the administration's own estimate.",
      'The hard truth is that years of kicking the can down the road has cost taxpayers more, not less.',
      'We commend the board majority for acting. Now they need to follow this vote with a long-term infrastructure plan.',
    ],
    tags: ['opinion', 'politics', 'infrastructure', 'government'],
    locked: true,
    featured: false,
  },
  {
    id: 9,
    slug: 'letter-support-local-businesses',
    section: 'opinion',
    title: 'Letter: Support Local Businesses — They Support Us',
    byline: 'Margaret Holbrook, St. Charles',
    date: 'April 26, 2026',
    category: 'Letter to the Editor',
    excerpt: 'As the downtown shopping season picks up, every dollar spent locally stays in our community in ways that big-box spending cannot match.',
    body: [
      'As spring arrives and the downtown shopping season picks up, I want to remind my neighbors of something easy to forget in a world of one-click ordering: local businesses are the backbone of what makes Fox Valley worth living in.',
      "When you buy from a shop on State Street or Third Street, that owner is the person who sponsors your kid's Little League team and shows up at city hall to fight for a stoplight at a dangerous intersection.",
      "Amazon doesn't do that. Walmart doesn't do that.",
      "I'm asking us to think before defaulting to the easiest option. Give the local place a shot first.",
      '— Margaret Holbrook, St. Charles',
    ],
    tags: ['opinion', 'business-and-finance', 'community'],
    locked: false,
    featured: false,
  },
  {
    id: 10,
    slug: 'commentary-election-results-fox-valley',
    section: 'opinion',
    title: "Commentary: What April's Results Mean for Fox Valley's Political Future",
    byline: 'James Kearney, Political Analyst',
    date: 'April 25, 2026',
    category: 'Commentary',
    excerpt: "Shifting margins in suburban precincts signal a realignment that neither party has fully grasped.",
    body: [
      "The numbers from Tuesday's consolidated election are in, and if you know where to look, they tell a story that goes well beyond who won and lost.",
      'In three Kane County precincts that voted reliably Republican as recently as 2020, margins have shrunk to single digits.',
      "What's driving it? Partly demographics: younger, more educated families have continued to move into the Fox Valley corridor.",
      "But it's also about local issues. Voters mentioned school board controversies, water quality concerns, and road conditions.",
      'Candidates who want to win here in 2028 would do well to pay attention.',
    ],
    tags: ['opinion', 'politics', 'elections'],
    locked: true,
    featured: false,
  },
  {
    id: 17,
    slug: 'letter-school-funding-band-aid',
    section: 'opinion',
    title: 'Letter: Our Schools Deserve More Than Band-Aid Budgets',
    byline: 'David Prentiss, Batavia',
    date: 'April 24, 2026',
    category: 'Letter to the Editor',
    excerpt: 'Another year, another round of cuts to extracurriculars and classroom aides while administrators talk about doing more with less.',
    body: [
      'Another school budget season, another round of cuts to extracurriculars, classroom aides, and building maintenance while administrators offer the same tired phrase: doing more with less.',
      "I have two kids in District 101. I've watched class sizes grow and elective offerings shrink for four consecutive years. At some point, 'more with less' just means less.",
      'The state funding formula sends more dollars to our district than it did five years ago, but local property tax revenue has not kept pace with inflation or enrollment growth.',
      'Our school board has tough choices to make. But the framing of "fiscal responsibility" should not become cover for a slow erosion of the educational experience our kids deserve.',
      '— David Prentiss, Batavia',
    ],
    tags: ['opinion', 'education', 'politics'],
    locked: false,
    featured: false,
  },
  {
    id: 18,
    slug: 'commentary-suburban-sprawl',
    section: 'opinion',
    title: "Commentary: Suburban Sprawl Is Eating the Fox Valley's Green Space",
    byline: 'Ellen Marsh, Conservation Advocate',
    date: 'April 23, 2026',
    category: 'Commentary',
    excerpt: "Three more farmland parcels approved for residential development this month. When do we say enough?",
    body: [
      "Three more farmland parcels received preliminary development approval from Kane County planners this month. Combined, they represent 340 acres that will be converted from agricultural land to residential subdivisions.",
      'This is not an isolated trend. Over the past decade, Kane and Kendall counties have lost more than 12,000 acres of farmland and natural open space to development — an area roughly the size of the city of Aurora.',
      'The fiscal argument for development is well-rehearsed: new housing brings property tax revenue, new residents support local businesses, growth is good. But the math rarely holds up over time.',
      'Infrastructure costs for new subdivisions — roads, water, sewer, schools — routinely exceed the tax revenue they generate in their first decade. The region\'s existing residents subsidize the expansion.',
      'Fox Valley forest preserve and park district boards have done admirable work protecting corridors. But they cannot buy fast enough to outpace the approvals.',
    ],
    tags: ['opinion', 'environment', 'government'],
    locked: true,
    featured: false,
  },
  {
    id: 19,
    slug: 'editorial-transit-investment',
    section: 'opinion',
    title: "Editorial: Transit Investment Can't Wait Another Decade",
    byline: 'Tribune Editorial Board',
    date: 'April 22, 2026',
    category: 'Editorial',
    excerpt: "The Metra BNSF line serves one corridor. The rest of the Fox Valley moves entirely by car. That needs to change.",
    body: [
      "The Fox Valley is one of the most car-dependent regions in metropolitan Chicago. The Metra BNSF line serves communities along one corridor; residents everywhere else move entirely by automobile or not at all.",
      "That reality shapes everything: traffic congestion, air quality, housing affordability, and the daily lives of the thousands of residents who don't drive — seniors, people with disabilities, workers who can't afford a car.",
      'The Regional Transportation Authority has studied Fox Valley transit needs repeatedly. The studies gather dust. The political will to fund solutions has never materialized.',
      "A bus rapid transit corridor on Route 31 connecting Aurora to Elgin has been proposed, shelved, and proposed again for more than 15 years. It would cost a fraction of the road expansion projects this region routinely approves without controversy.",
      'The question is not whether we can afford to invest in transit. It is whether we can afford not to.',
    ],
    tags: ['opinion', 'politics', 'transportation', 'government'],
    locked: true,
    featured: false,
  },

  // ── LOCAL POLITICS ────────────────────────────────────────────────────────
  {
    id: 20,
    slug: 'elgin-mayoral-race-four-candidates',
    section: 'local-politics',
    title: 'Elgin Mayoral Race Draws Four Candidates as Filing Deadline Passes',
    byline: 'Political Reporter',
    date: 'April 28, 2026',
    category: 'Elections',
    excerpt: 'Incumbent Mayor David Kaptain faces three challengers in the November municipal election, the most competitive mayoral field Elgin has seen in 16 years.',
    body: [
      "Incumbent Mayor David Kaptain will face three challengers in November's municipal election after the filing deadline passed Friday, producing the most competitive mayoral field Elgin has seen in 16 years.",
      'Challenging Kaptain are: Councilwoman Rosa Santana, 44, a small business owner and 8-year council veteran who has been critical of the city\'s downtown development spending; former City Administrator Greg Nolan, 58, who led Elgin\'s operations from 2011 to 2019; and community activist Marcus Thibodeau, 36, a first-time candidate focused on police accountability and affordable housing.',
      'Kaptain, who has served as mayor since 2011, said he is running on his record of fiscal stability and downtown revitalization. "Elgin is in a fundamentally stronger position than it was 15 years ago," he said. "I want to see that work through."',
      'Santana framed her campaign around redirecting development dollars toward neighborhoods. "Downtown looks beautiful, but drive six blocks in any direction and tell me if the investment is equally distributed," she said at a kickoff event Thursday.',
      'Early polling, commissioned by the Tribune, shows Kaptain with 38% support, Santana at 27%, Nolan at 16%, and Thibodeau at 9%, with 10% undecided.',
    ],
    tags: ['local-politics', 'politics', 'elections'],
    locked: true,
    featured: true,
  },
  {
    id: 21,
    slug: 'kane-county-district-2-supervisor',
    section: 'local-politics',
    title: 'Kane County District 2 Supervisor Contest Heats Up with Challenger Announcement',
    byline: 'Political Reporter',
    date: 'April 27, 2026',
    category: 'County Government',
    excerpt: 'Former St. Charles alderman Patrick Dunne announced his candidacy Tuesday, setting up a fall contest against 12-year incumbent James Harrington.',
    body: [
      'Former St. Charles alderman Patrick Dunne announced Tuesday he will challenge 12-year Kane County District 2 Supervisor James Harrington in November, setting up the most closely watched county race of the cycle.',
      'Dunne, 51, served three terms on the St. Charles City Council before stepping down in 2023. He said his campaign will focus on property tax relief, rural road maintenance, and increased transparency in county contracting.',
      '"Kane County residents deserve to know how their money is being spent," Dunne said at an announcement event at the St. Charles Elks Lodge. "Twelve years is a long time to hold any office without serious accountability."',
      'Harrington, 64, dismissed the challenge as political opportunism. "I\'ve delivered consistent results for District 2 — lower assessed tax rates, new park improvements, and infrastructure investment," he said in a statement. "My record speaks for itself."',
      'District 2 covers the townships of St. Charles, Geneva, and Campton, with a registered voter population of approximately 42,000.',
    ],
    tags: ['local-politics', 'politics', 'government', 'elections'],
    locked: true,
    featured: false,
  },
  {
    id: 22,
    slug: 'school-board-elections-contested-races',
    section: 'local-politics',
    title: 'Three Contested School Board Races Will Shape District Futures This Spring',
    byline: 'Education Reporter',
    date: 'April 26, 2026',
    category: 'Education / Elections',
    excerpt: 'Contested seats in Districts 101, 303, and U-46 feature sharp disagreements over curriculum, budget priorities, and administrative accountability.',
    body: [
      'Three of the Fox Valley\'s largest school districts will hold contested board elections this spring, with races in Batavia Unit District 101, St. Charles Community Unit 303, and Elgin Area School District U-46 drawing unusual levels of organized voter engagement on both sides.',
      'In District 101, two incumbent board members face challengers backed by a newly formed parents\' group calling for greater transparency in curriculum decisions. The incumbents have dismissed the challenge as an import of national culture-war politics into a local race.',
      'In District 303, the central issue is a proposed $48 million facilities referendum on the same ballot. Three candidates support the referendum; two oppose it, arguing the district should first address what they call administrative bloat.',
      'The U-46 race is the most crowded, with six candidates competing for three seats. The district\'s handling of a 2024 financial audit finding — which identified $2.3 million in improperly documented expenditures — has dominated candidate forums.',
      'Early voting begins April 30. Election Day is May 12.',
    ],
    tags: ['local-politics', 'politics', 'elections', 'education'],
    locked: true,
    featured: false,
  },
  {
    id: 23,
    slug: 'st-charles-zoning-downtown',
    section: 'local-politics',
    title: 'St. Charles City Council Approves Controversial Downtown Zoning Changes in 4-3 Vote',
    byline: 'Tribune Staff',
    date: 'April 25, 2026',
    category: 'City Government',
    excerpt: 'The narrow vote allows mixed-use buildings up to six stories on four parcels along First Street, overriding a planning commission recommendation to cap heights at four stories.',
    body: [
      'The St. Charles City Council voted 4-3 Monday night to approve zoning amendments that will allow mixed-use buildings of up to six stories on four parcels along First Street, overriding a planning commission recommendation to cap new construction at four stories.',
      'The vote capped a contentious six-month process that drew more than 200 public comments, with downtown business owners largely supportive and residential neighbors strongly opposed.',
      '"This is about keeping downtown economically vital for the next 20 years," said Alderman Pat Heinen, who voted yes. "If we cap height now, we\'re capping potential."',
      'Alderman Lori Swanson, who voted no, argued the decision prioritized developer interests over community character. "Our historic downtown is not a commodity," she said. "Once we allow six-story buildings on First Street, that character is gone."',
      'Developers have 18 months to submit building permit applications under the approved zoning. Two projects are reportedly in early planning stages.',
    ],
    tags: ['local-politics', 'politics', 'government'],
    locked: true,
    featured: false,
  },
  {
    id: 24,
    slug: 'state-house-district-49-special-election',
    section: 'local-politics',
    title: 'Special Election Called for State House District 49 After Resignation',
    byline: 'Political Reporter',
    date: 'April 24, 2026',
    category: 'State Government',
    excerpt: "Rep. Colleen Conway's departure to take a position in the governor's office triggers a vacancy the parties will fill through their own selection processes before a general election.",
    body: [
      "Gov. JB Pritzker's office announced Friday that Rep. Colleen Conway, who represented State House District 49 since 2018, has resigned to become the state's Deputy Director of Economic Development, triggering a special election process for her Kane County seat.",
      'Under state law, both parties\' precinct committeemen in the district will convene separately to nominate candidates to fill the vacancy. The nominees will then face each other in a special general election expected to be scheduled for late summer or early fall.',
      'District 49, which covers portions of Batavia, Geneva, and unincorporated Kane County, has been a competitive swing district. Conway won her last race by 7 points; her predecessor won by 4.',
      'Several names have been floated as potential Democratic nominees, including Batavia City Councilman Eric Swanson and former District 101 school board president Janet Kowalski.',
      'The Illinois Republican Party declined to name potential candidates but confirmed the precinct committee process would begin within 30 days.',
    ],
    tags: ['local-politics', 'politics', 'elections'],
    locked: true,
    featured: false,
  },
  {
    id: 25,
    slug: 'fox-valley-mayoral-forum',
    section: 'local-politics',
    title: 'Candidates Face Off in First Fox Valley Mayoral Forum of 2026',
    byline: 'Political Reporter',
    date: 'April 23, 2026',
    category: 'Elections',
    excerpt: 'Candidates from three Fox Valley municipalities squared off Wednesday on housing affordability, public safety staffing, and development incentives in a forum hosted by the Fox Valley Chamber of Commerce.',
    body: [
      'Eleven municipal candidates from Elgin, Aurora, and Batavia squared off Wednesday evening in the first major Fox Valley mayoral forum of the 2026 election cycle, hosted by the Fox Valley Chamber of Commerce at the Pheasant Run Convention Center.',
      "Housing affordability dominated the first hour. Aurora mayoral candidates clashed over the city's use of tax increment financing for downtown projects, with challenger Maria Torres arguing the TIF districts have diverted funds from affordable housing for too long.",
      '"We\'ve been told for 15 years that TIF investment will trickle out to neighborhoods," Torres said. "I\'m still waiting."',
      'On public safety, Elgin candidates split sharply on whether to pursue a new collective bargaining agreement with the police union or wait for the results of an ongoing staffing study before negotiations resume.',
      "The forum drew an audience of approximately 300. The Tribune's full candidate Q&A coverage will appear in Sunday's print edition and online at foxvalleytribune.com.",
    ],
    tags: ['local-politics', 'politics', 'elections'],
    locked: false,
    featured: false,
  },
];
