export const COLORS = {
  primary: '#C41230',
  dark: '#1A1A1A',
  sectionNews: '#0D3B6E',
  sectionSports: '#1B5E20',
  sectionOpinion: '#4A148C',
  sectionLocalPolitics: '#92400E',
  sectionLifestyle: '#0F766E',
  gray: '#666666',
  lightGray: '#F7F7F7',
  border: '#E0E0E0',
};

export const SECTION_COLORS = {
  news: COLORS.sectionNews,
  sports: COLORS.sectionSports,
  opinion: COLORS.sectionOpinion,
  'local-politics': COLORS.sectionLocalPolitics,
  lifestyle: COLORS.sectionLifestyle,
};

export const SECTION_LABELS = {
  news: 'News',
  sports: 'Sports',
  opinion: 'Opinion',
  'local-politics': 'Local Politics',
  lifestyle: 'Lifestyle',
};

export const SECTION_TAGLINES = {
  news: 'Local government, community, education, and business coverage from across the Fox Valley.',
  sports: 'High school, youth, and recreational sports from Kane and Kendall counties.',
  opinion: 'Editorials, letters to the editor, and commentary from Tribune staff and the community.',
  'local-politics': 'Elections, city councils, school boards, and the people who shape local government.',
  lifestyle: 'Home, wellness, food, personal growth, and the everyday fabric of Fox Valley life.',
};

export const PIANO_CONFIG = {
  AID: 'QiNgMM49pu',
  OFFER_ID: 'OFSKQS2JDQIS',
  SUBSCRIBER_RESOURCE_ID: null,
};

export const ARTICLES = [
  // ── NEWS ──────────────────────────────────────────────────────────────────
  {
    id: 1,
    slug: 'county-board-approves-road-repair-budget',
    section: 'news',
    title: 'County Board Approves $2.3M Road Repair Budget for 2026',
    byline: 'Tribune Staff',
    date: 'April 28, 2026',
    category: 'Government',
    excerpt: 'The Kane County Board voted 18-3 Tuesday to approve a $2.3 million road repair budget for the 2026 fiscal year, prioritizing 14 miles of deteriorating county roads.',
    body: [
      'The Kane County Board voted 18-3 Tuesday to approve a $2.3 million road repair budget for the 2026 fiscal year, prioritizing 14 miles of deteriorating county roads that officials say have reached the end of their useful life.',
      'The measure allocates $1.4 million for resurfacing projects in the eastern district and $900,000 for drainage improvements on Route 47 north of Huntley. Work is expected to begin in late May and wrap up before first frost.',
      '"These roads have been on our radar for five years," said County Engineer Patricia Hollis. "We\'ve done everything we can to extend their life with patch repairs, but we\'ve reached the point where we need to invest properly."',
      'The funding comes from a combination of state transportation grants and county motor fuel tax revenues.',
      'Three board members voted against the measure, citing concerns about the bidding process and calling for more competitive contract solicitation.',
    ],
    tags: ['news', 'government', 'politics', 'infrastructure'],
    locked: true,
    featured: true,
  },
  {
    id: 2,
    slug: 'new-grocery-store-downtown-geneva',
    section: 'news',
    title: 'New Full-Service Grocery Store Planned for Downtown Geneva',
    byline: 'Tribune Staff',
    date: 'April 27, 2026',
    category: 'Business',
    excerpt: 'A Chicago-based grocery chain announced plans to open a 28,000-square-foot store in the former Sears building on State Street.',
    body: [
      'A Chicago-based grocery chain announced plans Monday to open a 28,000-square-foot store in the former Sears building on State Street, ending a three-year search by city planners for an anchor tenant.',
      'Fresh Thyme Market, which operates 24 stores in the Midwest, signed a 15-year lease and expects to open by March 2027 pending city approvals.',
      '"This is exactly the kind of tenant we\'ve been working to attract," said Geneva City Manager Rob Godskesen.',
      'The store will employ approximately 85 full- and part-time workers and generate an estimated $180,000 in annual sales tax revenue for the city.',
    ],
    tags: ['news', 'business-and-finance', 'community'],
    locked: false,
    featured: false,
  },
  {
    id: 3,
    slug: 'school-district-teacher-shortage',
    section: 'news',
    title: 'School District Faces Growing Teacher Shortage Ahead of Fall',
    byline: 'Education Reporter',
    date: 'April 26, 2026',
    category: 'Education',
    excerpt: 'With 34 open teaching positions and hiring season underway, District 303 officials are weighing emergency certification programs and increased pay for hard-to-fill roles.',
    body: [
      'With 34 open teaching positions and the prime hiring season half over, School District 303 is facing its most acute staffing shortage in more than a decade.',
      'The vacancies span nearly every subject area but are most concentrated in special education, high school math, and elementary bilingual classrooms.',
      '"We\'re competing with every district in the region for the same pool of candidates," said Human Resources Director Tanya Ostrander.',
      'The board voted to authorize emergency hiring measures including signing bonuses of up to $5,000 for high-need positions.',
      'Officials also said they are exploring a grow-your-own pipeline program that would offer tuition assistance to paraprofessionals already working in the district.',
    ],
    tags: ['news', 'education', 'family-and-parenting'],
    locked: true,
    featured: false,
  },
  {
    id: 4,
    slug: 'water-main-break-route-31',
    section: 'news',
    title: 'Water Main Break Closes Lanes on Route 31 Near Elgin',
    byline: 'Tribune Staff',
    date: 'April 25, 2026',
    category: 'Local',
    excerpt: 'A 12-inch water main ruptured Tuesday morning, closing two northbound lanes and cutting service to approximately 800 customers.',
    body: [
      'A 12-inch water main ruptured early Tuesday morning near the intersection of Route 31 and Bowes Road, closing two northbound lanes and cutting water service to approximately 800 customers.',
      'Crews from the Fox Valley Water Authority responded at 4:42 a.m. and worked through the afternoon to isolate the break and restore pressure.',
      'Service was fully restored by 6:30 p.m. Northbound lanes on Route 31 remained partially closed through Wednesday morning.',
      'The main, installed in 1987, had been flagged in the authority\'s infrastructure assessment as nearing the end of its expected service life.',
    ],
    tags: ['news', 'infrastructure', 'local-government'],
    locked: false,
    featured: false,
  },
  {
    id: 11,
    slug: 'aurora-community-center-east-side',
    section: 'news',
    title: 'Aurora Breaks Ground on $4.1M East Side Community Center',
    byline: 'Tribune Staff',
    date: 'April 24, 2026',
    category: 'Community',
    excerpt: 'City and state officials gathered Tuesday for a groundbreaking ceremony on a long-awaited community center that will serve an estimated 1,200 residents per week.',
    body: [
      'City and state officials gathered Tuesday morning on a vacant lot at the corner of New York and Hill Avenue for the groundbreaking of a $4.1 million community center that will serve Aurora\'s east side.',
      'The 18,000-square-foot facility will include a gym, after-school tutoring rooms, senior programming space, and a commercial kitchen for community food programs.',
      '"This neighborhood has waited a long time for this investment," said Mayor Richard Irvin. "It\'s a down payment on what this community deserves."',
      'Funding comes from a mix of federal Community Development Block Grant dollars, state capital appropriations secured by Rep. Maura Hirschauer, and a $600,000 private donation from the Fox Valley Community Foundation.',
      'The center is expected to open by spring 2027. A nonprofit operator has not yet been selected; the city expects to issue an RFP this summer.',
    ],
    tags: ['news', 'community', 'government'],
    locked: true,
    featured: false,
  },
  {
    id: 12,
    slug: 'fox-valley-hospital-expansion',
    section: 'news',
    title: 'Fox Valley Regional Hospital Expansion Will Add 80 Beds, New ER Wing',
    byline: 'Health Reporter',
    date: 'April 23, 2026',
    category: 'Health',
    excerpt: 'The $112 million expansion project will nearly double the emergency department\'s capacity and add a new cardiac care unit by late 2028.',
    body: [
      'Fox Valley Regional Medical Center announced Tuesday a $112 million expansion that will add 80 inpatient beds and nearly double the capacity of its emergency department, addressing wait times that have grown steadily since 2022.',
      'The project, funded through a combination of hospital revenue bonds and a state health infrastructure grant, will also include a dedicated cardiac care unit and an expanded surgical suite.',
      '"The Fox Valley\'s population has grown significantly, and our facility needs to grow with it," said CEO Dr. Linda Castellano. "This expansion is essential to maintaining the standard of care our community expects."',
      'Construction is expected to begin in late summer. The expanded ER wing is projected to open in phases, with the first phase operational by early 2028.',
      'The hospital currently sees approximately 65,000 emergency visits per year — up from 44,000 a decade ago. The new ER will be designed to handle up to 90,000 visits annually.',
    ],
    tags: ['news', 'health'],
    locked: true,
    featured: false,
  },
  {
    id: 13,
    slug: 'batavia-farmers-market-returns',
    section: 'news',
    title: "Batavia Farmer's Market Returns May 10 with Record 60 Vendors",
    byline: 'Tribune Staff',
    date: 'April 22, 2026',
    category: 'Community',
    excerpt: "This year's market will feature a record 60 vendors, a new prepared-food tent, and extended Saturday hours through October.",
    body: [
      "The Batavia Farmer's Market opens for its 28th season on Saturday, May 10, with a record 60 vendors — up from 47 last year — and several new features organizers say reflect growing demand.",
      'New this year: a prepared-food tent with eight rotating food vendors, a kids\' activity area sponsored by the Batavia Park District, and extended hours on Saturdays from 7 a.m. to 1 p.m.',
      '"We had a waiting list of vendors for the first time in our history," said Market Director Angela Smits. "The community\'s appetite for local food has never been stronger."',
      "The market runs Saturdays through October 25 in the city's downtown district on Wilson Street. A Wednesday evening market launches June 4 and runs through August.",
    ],
    tags: ['news', 'food-and-drink', 'community'],
    locked: false,
    featured: false,
  },

  // ── SPORTS ────────────────────────────────────────────────────────────────
  {
    id: 5,
    slug: 'batavia-bulldogs-regional-championship',
    section: 'sports',
    title: 'Batavia Bulldogs Capture Regional Title in Overtime Thriller',
    byline: 'Tribune Sports',
    date: 'April 28, 2026',
    category: 'High School Soccer',
    excerpt: 'Senior midfielder Connor Walsh scored in the 94th minute to lift Batavia past St. Charles East 2-1 in a regional boys soccer final.',
    body: [
      'Senior midfielder Connor Walsh scored in the 94th minute to lift the Batavia Bulldogs past St. Charles East 2-1 in a regional boys soccer final Saturday.',
      'Walsh collected a through ball from sophomore Mateo Hernandez and beat the keeper low to the left post.',
      '"I was just trying to stay patient and wait for my moment," Walsh said afterward.',
      'The Bulldogs, now 16-4-2, advance to the sectional semifinals Wednesday against Wheaton Warrenville South.',
      'St. Charles East had taken the lead at 62 minutes on a free kick from Damian Torres before Batavia equalized on a penalty by junior Kyle Peterson at 71 minutes.',
    ],
    tags: ['sports', 'soccer', 'high-school-sports'],
    locked: true,
    featured: true,
  },
  {
    id: 6,
    slug: 'st-charles-north-wrestler-state-title',
    section: 'sports',
    title: 'St. Charles North Senior Wins State Wrestling Title at 170 Pounds',
    byline: 'Tribune Sports',
    date: 'April 26, 2026',
    category: 'High School Wrestling',
    excerpt: 'Marcus Webb pinned his opponent in 1:47 of the championship match to give St. Charles North its first individual state wrestling title since 2019.',
    body: [
      'Marcus Webb pinned his Springfield Southeast opponent in 1:47 of the championship match Saturday to give St. Charles North its first individual state title in wrestling since 2019.',
      'Webb, a three-time state qualifier who finished third a year ago, was dominant throughout the tournament, allowing just five points across five matches.',
      '"This is what I\'ve worked for since I was a freshman," said Webb, who finished the season 41-1.',
      'Webb committed to the University of Illinois in February.',
    ],
    tags: ['sports', 'wrestling', 'high-school-sports'],
    locked: true,
    featured: false,
  },
  {
    id: 7,
    slug: 'youth-soccer-league-expansion',
    section: 'sports',
    title: 'Fox Valley Youth Soccer League Expanding to Three New Communities',
    byline: 'Tribune Staff',
    date: 'April 24, 2026',
    category: 'Youth Sports',
    excerpt: 'The Fox Valley Youth Soccer League will add divisions in Carpentersville, Burlington, and Sleepy Hollow starting with the fall 2026 season.',
    body: [
      'The Fox Valley Youth Soccer League announced Thursday it will expand into three new communities — Carpentersville, Burlington, and Sleepy Hollow — beginning with the fall 2026 season.',
      'The expansion adds approximately 340 players and nine new teams to a league that currently serves more than 2,400 youth athletes across 18 communities.',
      '"The demand in these communities has been there for years," said league director Angela Moreno.',
      'Registration for fall leagues opens May 15 at foxvalleysoccer.org.',
    ],
    tags: ['sports', 'soccer', 'family-and-parenting', 'youth-sports'],
    locked: false,
    featured: false,
  },
  {
    id: 14,
    slug: 'olivia-park-northwestern-swim',
    section: 'sports',
    title: 'Geneva Senior Olivia Park Signs with Northwestern Swimming',
    byline: 'Tribune Sports',
    date: 'April 25, 2026',
    category: 'High School Swimming',
    excerpt: 'The four-time state qualifier and two-time individual champion will join the Wildcats\' program in the fall, the first Geneva swimmer to commit to a Big Ten program since 2019.',
    body: [
      'Geneva High School senior Olivia Park signed her National Letter of Intent to swim at Northwestern University on Wednesday, becoming the first Geneva swimmer to commit to a Big Ten program in seven years.',
      'Park, a four-time state qualifier and two-time individual state champion in the 200 freestyle, chose Northwestern over offers from Michigan State, Wisconsin, and Indiana.',
      '"Northwestern felt like home from my first visit," Park said at a signing ceremony attended by teammates and coaches. "The academics are unbeatable and the program is on the rise."',
      'She finished this season with a personal-best 1:47.31 in the 200 freestyle — the fourth-fastest time in Illinois this year.',
      'Geneva head coach Dana Rekowski called Park "the most complete swimmer we\'ve developed in 15 years of this program." She will graduate in June and join Northwestern\'s roster in September.',
    ],
    tags: ['sports', 'swimming', 'high-school-sports'],
    locked: true,
    featured: false,
  },
  {
    id: 15,
    slug: 'fox-valley-marathon-returns',
    section: 'sports',
    title: 'Fox Valley Marathon Returns After Three-Year Hiatus',
    byline: 'Tribune Sports',
    date: 'April 23, 2026',
    category: 'Road Racing',
    excerpt: 'Registration is open for the October 5 race, which will follow a redesigned course through Geneva, Batavia, and St. Charles.',
    body: [
      'The Fox Valley Marathon is back. Race organizers announced Wednesday that the event — which last ran in 2022 before a three-year pause — will return on October 5 with a redesigned course and a new title sponsor.',
      'The 26.2-mile course winds through Geneva, Batavia, and St. Charles along the Fox River Trail, with the finish line at the Pottawatomie Park amphitheater in St. Charles.',
      'Registration is open at foxvalleymarathon.com. Early-bird pricing is $95 for the full marathon and $65 for the half marathon through June 1.',
      '"We heard from runners every year asking when we were coming back," said race director Kevin Hollenbeck. "The community support for this event has always been exceptional."',
    ],
    tags: ['sports', 'running', 'road-racing'],
    locked: false,
    featured: false,
  },
  {
    id: 16,
    slug: 'spring-baseball-preview',
    section: 'sports',
    title: 'Spring Baseball Preview: Five Fox Valley Teams to Watch',
    byline: 'Tribune Sports',
    date: 'April 21, 2026',
    category: 'High School Baseball',
    excerpt: 'Batavia, St. Charles East, Geneva, Kaneland, and Oswego East enter the postseason with legitimate sectional championship aspirations.',
    body: [
      'With sectional play approaching, five Fox Valley programs have emerged as legitimate contenders for deep playoff runs. Here\'s a look at each.',
      'Batavia (18-3) leads the Upstate Eight with a rotation anchored by junior right-hander Drew Patterson, who carries a 0.91 ERA and has struck out 87 batters in 54 innings.',
      'St. Charles East (16-4) is powered by one of the conference\'s best lineups, averaging 7.4 runs per game behind senior centerfielder Jake Morales (.418 average, 6 home runs).',
      'Geneva (14-6) is the most balanced of the contenders — no single standout but deep pitching and a defense that has committed just nine errors all season.',
      'Kaneland (13-7) and Oswego East (13-6) both feature elite arms and the kind of veteran experience that tends to matter in elimination games.',
    ],
    tags: ['sports', 'baseball', 'high-school-sports'],
    locked: true,
    featured: false,
  },

  // ── OPINION ───────────────────────────────────────────────────────────────
  {
    id: 8,
    slug: 'editorial-infrastructure-investment',
    section: 'opinion',
    title: 'Editorial: The Time to Fix Our Roads Is Now',
    byline: 'Tribune Editorial Board',
    date: 'April 28, 2026',
    category: 'Editorial',
    excerpt: "The county board's road repair vote is welcome — but it's a down payment on years of deferred maintenance.",
    body: [
      "Tuesday's county board vote approving $2.3 million for road repairs is welcome news for drivers who have navigated the same crumbling county roads for the better part of a decade. But it's a down payment, not a solution.",
      "Kane County's infrastructure maintenance backlog now exceeds $47 million by the administration's own estimate.",
      'The hard truth is that years of kicking the can down the road has cost taxpayers more, not less.',
      'We commend the board majority for acting. Now they need to follow this vote with a long-term infrastructure plan.',
    ],
    tags: ['opinion', 'politics', 'infrastructure', 'government'],
    locked: true,
    featured: false,
  },
  {
    id: 9,
    slug: 'letter-support-local-businesses',
    section: 'opinion',
    title: 'Letter: Support Local Businesses — They Support Us',
    byline: 'Margaret Holbrook, St. Charles',
    date: 'April 26, 2026',
    category: 'Letter to the Editor',
    excerpt: 'As the downtown shopping season picks up, every dollar spent locally stays in our community in ways that big-box spending cannot match.',
    body: [
      'As spring arrives and the downtown shopping season picks up, I want to remind my neighbors of something easy to forget in a world of one-click ordering: local businesses are the backbone of what makes Fox Valley worth living in.',
      "When you buy from a shop on State Street or Third Street, that owner is the person who sponsors your kid's Little League team and shows up at city hall to fight for a stoplight at a dangerous intersection.",
      "Amazon doesn't do that. Walmart doesn't do that.",
      "I'm asking us to think before defaulting to the easiest option. Give the local place a shot first.",
      '— Margaret Holbrook, St. Charles',
    ],
    tags: ['opinion', 'business-and-finance', 'community'],
    locked: false,
    featured: false,
  },
  {
    id: 10,
    slug: 'commentary-election-results-fox-valley',
    section: 'opinion',
    title: "Commentary: What April's Results Mean for Fox Valley's Political Future",
    byline: 'James Kearney, Political Analyst',
    date: 'April 25, 2026',
    category: 'Commentary',
    excerpt: "Shifting margins in suburban precincts signal a realignment that neither party has fully grasped.",
    body: [
      "The numbers from Tuesday's consolidated election are in, and if you know where to look, they tell a story that goes well beyond who won and lost.",
      'In three Kane County precincts that voted reliably Republican as recently as 2020, margins have shrunk to single digits.',
      "What's driving it? Partly demographics: younger, more educated families have continued to move into the Fox Valley corridor.",
      "But it's also about local issues. Voters mentioned school board controversies, water quality concerns, and road conditions.",
      'Candidates who want to win here in 2028 would do well to pay attention.',
    ],
    tags: ['opinion', 'politics', 'elections'],
    locked: true,
    featured: false,
  },
  {
    id: 17,
    slug: 'letter-school-funding-band-aid',
    section: 'opinion',
    title: 'Letter: Our Schools Deserve More Than Band-Aid Budgets',
    byline: 'David Prentiss, Batavia',
    date: 'April 24, 2026',
    category: 'Letter to the Editor',
    excerpt: 'Another year, another round of cuts to extracurriculars and classroom aides while administrators talk about doing more with less.',
    body: [
      'Another school budget season, another round of cuts to extracurriculars, classroom aides, and building maintenance while administrators offer the same tired phrase: doing more with less.',
      "I have two kids in District 101. I've watched class sizes grow and elective offerings shrink for four consecutive years. At some point, 'more with less' just means less.",
      'The state funding formula sends more dollars to our district than it did five years ago, but local property tax revenue has not kept pace with inflation or enrollment growth.',
      'Our school board has tough choices to make. But the framing of "fiscal responsibility" should not become cover for a slow erosion of the educational experience our kids deserve.',
      '— David Prentiss, Batavia',
    ],
    tags: ['opinion', 'education', 'politics'],
    locked: false,
    featured: false,
  },
  {
    id: 18,
    slug: 'commentary-suburban-sprawl',
    section: 'opinion',
    title: "Commentary: Suburban Sprawl Is Eating the Fox Valley's Green Space",
    byline: 'Ellen Marsh, Conservation Advocate',
    date: 'April 23, 2026',
    category: 'Commentary',
    excerpt: "Three more farmland parcels approved for residential development this month. When do we say enough?",
    body: [
      "Three more farmland parcels received preliminary development approval from Kane County planners this month. Combined, they represent 340 acres that will be converted from agricultural land to residential subdivisions.",
      'This is not an isolated trend. Over the past decade, Kane and Kendall counties have lost more than 12,000 acres of farmland and natural open space to development — an area roughly the size of the city of Aurora.',
      'The fiscal argument for development is well-rehearsed: new housing brings property tax revenue, new residents support local businesses, growth is good. But the math rarely holds up over time.',
      'Infrastructure costs for new subdivisions — roads, water, sewer, schools — routinely exceed the tax revenue they generate in their first decade. The region\'s existing residents subsidize the expansion.',
      'Fox Valley forest preserve and park district boards have done admirable work protecting corridors. But they cannot buy fast enough to outpace the approvals.',
    ],
    tags: ['opinion', 'environment', 'government'],
    locked: true,
    featured: false,
  },
  {
    id: 19,
    slug: 'editorial-transit-investment',
    section: 'opinion',
    title: "Editorial: Transit Investment Can't Wait Another Decade",
    byline: 'Tribune Editorial Board',
    date: 'April 22, 2026',
    category: 'Editorial',
    excerpt: "The Metra BNSF line serves one corridor. The rest of the Fox Valley moves entirely by car. That needs to change.",
    body: [
      "The Fox Valley is one of the most car-dependent regions in metropolitan Chicago. The Metra BNSF line serves communities along one corridor; residents everywhere else move entirely by automobile or not at all.",
      "That reality shapes everything: traffic congestion, air quality, housing affordability, and the daily lives of the thousands of residents who don't drive — seniors, people with disabilities, workers who can't afford a car.",
      'The Regional Transportation Authority has studied Fox Valley transit needs repeatedly. The studies gather dust. The political will to fund solutions has never materialized.',
      "A bus rapid transit corridor on Route 31 connecting Aurora to Elgin has been proposed, shelved, and proposed again for more than 15 years. It would cost a fraction of the road expansion projects this region routinely approves without controversy.",
      'The question is not whether we can afford to invest in transit. It is whether we can afford not to.',
    ],
    tags: ['opinion', 'politics', 'transportation', 'government'],
    locked: true,
    featured: false,
  },

  // ── LOCAL POLITICS ────────────────────────────────────────────────────────
  {
    id: 20,
    slug: 'elgin-mayoral-race-four-candidates',
    section: 'local-politics',
    title: 'Elgin Mayoral Race Draws Four Candidates as Filing Deadline Passes',
    byline: 'Political Reporter',
    date: 'April 28, 2026',
    category: 'Elections',
    excerpt: 'Incumbent Mayor David Kaptain faces three challengers in the November municipal election, the most competitive mayoral field Elgin has seen in 16 years.',
    body: [
      "Incumbent Mayor David Kaptain will face three challengers in November's municipal election after the filing deadline passed Friday, producing the most competitive mayoral field Elgin has seen in 16 years.",
      'Challenging Kaptain are: Councilwoman Rosa Santana, 44, a small business owner and 8-year council veteran who has been critical of the city\'s downtown development spending; former City Administrator Greg Nolan, 58, who led Elgin\'s operations from 2011 to 2019; and community activist Marcus Thibodeau, 36, a first-time candidate focused on police accountability and affordable housing.',
      'Kaptain, who has served as mayor since 2011, said he is running on his record of fiscal stability and downtown revitalization. "Elgin is in a fundamentally stronger position than it was 15 years ago," he said. "I want to see that work through."',
      'Santana framed her campaign around redirecting development dollars toward neighborhoods. "Downtown looks beautiful, but drive six blocks in any direction and tell me if the investment is equally distributed," she said at a kickoff event Thursday.',
      'Early polling, commissioned by the Tribune, shows Kaptain with 38% support, Santana at 27%, Nolan at 16%, and Thibodeau at 9%, with 10% undecided.',
    ],
    tags: ['local-politics', 'politics', 'elections'],
    locked: true,
    featured: true,
  },
  {
    id: 21,
    slug: 'kane-county-district-2-supervisor',
    section: 'local-politics',
    title: 'Kane County District 2 Supervisor Contest Heats Up with Challenger Announcement',
    byline: 'Political Reporter',
    date: 'April 27, 2026',
    category: 'County Government',
    excerpt: 'Former St. Charles alderman Patrick Dunne announced his candidacy Tuesday, setting up a fall contest against 12-year incumbent James Harrington.',
    body: [
      'Former St. Charles alderman Patrick Dunne announced Tuesday he will challenge 12-year Kane County District 2 Supervisor James Harrington in November, setting up the most closely watched county race of the cycle.',
      'Dunne, 51, served three terms on the St. Charles City Council before stepping down in 2023. He said his campaign will focus on property tax relief, rural road maintenance, and increased transparency in county contracting.',
      '"Kane County residents deserve to know how their money is being spent," Dunne said at an announcement event at the St. Charles Elks Lodge. "Twelve years is a long time to hold any office without serious accountability."',
      'Harrington, 64, dismissed the challenge as political opportunism. "I\'ve delivered consistent results for District 2 — lower assessed tax rates, new park improvements, and infrastructure investment," he said in a statement. "My record speaks for itself."',
      'District 2 covers the townships of St. Charles, Geneva, and Campton, with a registered voter population of approximately 42,000.',
    ],
    tags: ['local-politics', 'politics', 'government', 'elections'],
    locked: true,
    featured: false,
  },
  {
    id: 22,
    slug: 'school-board-elections-contested-races',
    section: 'local-politics',
    title: 'Three Contested School Board Races Will Shape District Futures This Spring',
    byline: 'Education Reporter',
    date: 'April 26, 2026',
    category: 'Education / Elections',
    excerpt: 'Contested seats in Districts 101, 303, and U-46 feature sharp disagreements over curriculum, budget priorities, and administrative accountability.',
    body: [
      'Three of the Fox Valley\'s largest school districts will hold contested board elections this spring, with races in Batavia Unit District 101, St. Charles Community Unit 303, and Elgin Area School District U-46 drawing unusual levels of organized voter engagement on both sides.',
      'In District 101, two incumbent board members face challengers backed by a newly formed parents\' group calling for greater transparency in curriculum decisions. The incumbents have dismissed the challenge as an import of national culture-war politics into a local race.',
      'In District 303, the central issue is a proposed $48 million facilities referendum on the same ballot. Three candidates support the referendum; two oppose it, arguing the district should first address what they call administrative bloat.',
      'The U-46 race is the most crowded, with six candidates competing for three seats. The district\'s handling of a 2024 financial audit finding — which identified $2.3 million in improperly documented expenditures — has dominated candidate forums.',
      'Early voting begins April 30. Election Day is May 12.',
    ],
    tags: ['local-politics', 'politics', 'elections', 'education'],
    locked: true,
    featured: false,
  },
  {
    id: 23,
    slug: 'st-charles-zoning-downtown',
    section: 'local-politics',
    title: 'St. Charles City Council Approves Controversial Downtown Zoning Changes in 4-3 Vote',
    byline: 'Tribune Staff',
    date: 'April 25, 2026',
    category: 'City Government',
    excerpt: 'The narrow vote allows mixed-use buildings up to six stories on four parcels along First Street, overriding a planning commission recommendation to cap heights at four stories.',
    body: [
      'The St. Charles City Council voted 4-3 Monday night to approve zoning amendments that will allow mixed-use buildings of up to six stories on four parcels along First Street, overriding a planning commission recommendation to cap new construction at four stories.',
      'The vote capped a contentious six-month process that drew more than 200 public comments, with downtown business owners largely supportive and residential neighbors strongly opposed.',
      '"This is about keeping downtown economically vital for the next 20 years," said Alderman Pat Heinen, who voted yes. "If we cap height now, we\'re capping potential."',
      'Alderman Lori Swanson, who voted no, argued the decision prioritized developer interests over community character. "Our historic downtown is not a commodity," she said. "Once we allow six-story buildings on First Street, that character is gone."',
      'Developers have 18 months to submit building permit applications under the approved zoning. Two projects are reportedly in early planning stages.',
    ],
    tags: ['local-politics', 'politics', 'government'],
    locked: true,
    featured: false,
  },
  {
    id: 24,
    slug: 'state-house-district-49-special-election',
    section: 'local-politics',
    title: 'Special Election Called for State House District 49 After Resignation',
    byline: 'Political Reporter',
    date: 'April 24, 2026',
    category: 'State Government',
    excerpt: "Rep. Colleen Conway's departure to take a position in the governor's office triggers a vacancy the parties will fill through their own selection processes before a general election.",
    body: [
      "Gov. JB Pritzker's office announced Friday that Rep. Colleen Conway, who represented State House District 49 since 2018, has resigned to become the state's Deputy Director of Economic Development, triggering a special election process for her Kane County seat.",
      'Under state law, both parties\' precinct committeemen in the district will convene separately to nominate candidates to fill the vacancy. The nominees will then face each other in a special general election expected to be scheduled for late summer or early fall.',
      'District 49, which covers portions of Batavia, Geneva, and unincorporated Kane County, has been a competitive swing district. Conway won her last race by 7 points; her predecessor won by 4.',
      'Several names have been floated as potential Democratic nominees, including Batavia City Councilman Eric Swanson and former District 101 school board president Janet Kowalski.',
      'The Illinois Republican Party declined to name potential candidates but confirmed the precinct committee process would begin within 30 days.',
    ],
    tags: ['local-politics', 'politics', 'elections'],
    locked: true,
    featured: false,
  },
  {
    id: 25,
    slug: 'fox-valley-mayoral-forum',
    section: 'local-politics',
    title: 'Candidates Face Off in First Fox Valley Mayoral Forum of 2026',
    byline: 'Political Reporter',
    date: 'April 23, 2026',
    category: 'Elections',
    excerpt: 'Candidates from three Fox Valley municipalities squared off Wednesday on housing affordability, public safety staffing, and development incentives in a forum hosted by the Fox Valley Chamber of Commerce.',
    body: [
      'Eleven municipal candidates from Elgin, Aurora, and Batavia squared off Wednesday evening in the first major Fox Valley mayoral forum of the 2026 election cycle, hosted by the Fox Valley Chamber of Commerce at the Pheasant Run Convention Center.',
      "Housing affordability dominated the first hour. Aurora mayoral candidates clashed over the city's use of tax increment financing for downtown projects, with challenger Maria Torres arguing the TIF districts have diverted funds from affordable housing for too long.",
      '"We\'ve been told for 15 years that TIF investment will trickle out to neighborhoods," Torres said. "I\'m still waiting."',
      'On public safety, Elgin candidates split sharply on whether to pursue a new collective bargaining agreement with the police union or wait for the results of an ongoing staffing study before negotiations resume.',
      "The forum drew an audience of approximately 300. The Tribune's full candidate Q&A coverage will appear in Sunday's print edition and online at foxvalleytribune.com.",
    ],
    tags: ['local-politics', 'politics', 'elections'],
    locked: false,
    featured: false,
  },

  // ── LIFESTYLE ─────────────────────────────────────────────────────────────
  {
    id: 26,
    slug: 'small-space-big-style-fox-valley-interiors',
    section: 'lifestyle',
    title: 'Small Space, Big Style: How Fox Valley Homeowners Are Reinventing Their Interiors',
    byline: 'Tribune Lifestyle',
    date: 'May 8, 2026',
    category: 'Home & Design',
    excerpt: 'A wave of Fox Valley homeowners are turning compact rooms into purposeful, beautiful spaces — without major renovations.',
    body: [
      'In a split-level in St. Charles, a dining room that saw use three times a year is now a reading nook, a homework station, and the most-used room in the house. Its owner, Carla Wentz, made the transformation with $400 and a weekend.',
      '"We stopped decorating for the life we thought we were supposed to have," Wentz said. "Now the house actually reflects how we live."',
      'Across the Fox Valley, a quiet shift is underway in how suburban homeowners think about their interiors. Driven partly by the continued influence of remote work and partly by a broader cultural backlash to excess, many residents are scaling back furniture, rethinking room assignments, and investing in quality over quantity.',
      'Interior designer Rachel Koonce, who operates out of Geneva and serves clients across Kane County, says the shift has been consistent in her practice for about two years. "The brief used to be \'make it look like a magazine.\' Now it\'s \'make it work for us.\' That\'s actually more interesting to design for."',
      'Common moves she sees: converting formal dining rooms into dual-purpose offices, replacing oversized sectionals with two smaller sofas arranged for conversation, and committing to a tighter color palette — usually two neutrals and one accent — that makes even modest square footage feel intentional.',
      'For homeowners considering their own refresh, Koonce recommends starting with subtraction. "Remove half of what\'s on every surface. Live with that for two weeks. You\'ll know exactly what deserves to come back."',
    ],
    tags: ['lifestyle', 'home-design', 'interior', 'community'],
    locked: false,
    featured: true,
  },
  {
    id: 27,
    slug: 'fox-river-trail-fitness-guide',
    section: 'lifestyle',
    title: 'Walking the Fox River Trail: A Beginner\'s Guide to the Valley\'s Best Outdoor Workout',
    byline: 'Tribune Lifestyle',
    date: 'May 7, 2026',
    category: 'Wellness',
    excerpt: 'The Fox River Trail runs 40 miles through the heart of the valley. Here\'s how locals are using it as a fitness routine, not just a weekend walk.',
    body: [
      'The Fox River Trail stretches roughly 40 miles from Algonquin to Oswego, threading through Geneva, Batavia, St. Charles, and Aurora along the river\'s edge. For most people who live near it, it\'s a weekend destination. For a growing number of Fox Valley residents, it\'s the backbone of a daily fitness practice.',
      '"I walk four miles every morning before my kids wake up," said Diana Foss of Batavia, who started the habit in January 2025 and has kept it through every season. "It\'s the one non-negotiable in my day."',
      'Sports medicine physician Dr. Jim Okafor at Fox Valley Regional Medical Center says he recommends the trail regularly to patients. "Walking is underrated as a fitness modality. Thirty minutes of brisk walking five days a week produces measurable cardiovascular benefits. The trail makes it easy to actually do it."',
      'For beginners, the most accessible entry points include the Island Park trailhead in Geneva, the Pottawatomie Park access in St. Charles, and the Riverwalk connection in Aurora. All have parking, restrooms, and flat terrain suitable for any fitness level.',
      'More experienced trail users have developed structured routines: interval walking (alternating brisk and recovery pace), stair repeats at the Batavia Riverwalk, or longer weekend efforts of 10 to 15 miles that connect multiple communities.',
      'The trail is maintained by a patchwork of municipal park districts and the Illinois Department of Natural Resources. A full trail map and current surface conditions are available at foxrivertrail.org.',
    ],
    tags: ['lifestyle', 'wellness', 'fitness', 'outdoors'],
    locked: false,
    featured: false,
  },
  {
    id: 28,
    slug: 'meal-prep-fox-valley-home-cook',
    section: 'lifestyle',
    title: 'The Art of Meal Prep: A Fox Valley Home Cook\'s Weekly System',
    byline: 'Tribune Lifestyle',
    date: 'May 6, 2026',
    category: 'Food & Cooking',
    excerpt: 'Geneva resident Laura Simons feeds a family of five on weeknights with two hours of Sunday prep. She shares exactly how.',
    body: [
      'Every Sunday at 2 p.m., Geneva resident Laura Simons begins what she calls "the reset." Two hours later, her refrigerator holds roasted vegetables, a pot of grains, marinated proteins, and washed salad greens — the raw material for five nights of weeknight dinners.',
      '"I don\'t meal prep full recipes," Simons, 38, explained. "I prep components. Monday night I might do grain bowls. Tuesday the same roasted vegetables go into tacos. Wednesday they\'re in a frittata. The variety comes from how you combine things, not from cooking five different meals."',
      'The approach, sometimes called component cooking, has grown in popularity among working parents looking for a middle path between elaborate home cooking and daily takeout.',
      'Her weekly anchor: one large batch of a whole grain (farro, brown rice, or barley), two sheet pans of roasted vegetables, one protein prepared two ways (half simply seasoned, half marinated), and a large green salad kept undressed and sealed.',
      'Simons shops Wednesday evenings at the Batavia Farmer\'s Market or the Jewel on Kirk Road, building her prep list around what looks good rather than following a rigid plan. "Flexibility is the whole point. If you\'re too rigid, you fall off the system the first week something doesn\'t work out."',
      'For families just starting out, she recommends beginning with just one component — a pot of grains — for the first two weeks before adding others. "The habit matters more than the system. Start smaller than you think you need to."',
    ],
    tags: ['lifestyle', 'food-and-drink', 'cooking', 'family-and-parenting'],
    locked: true,
    featured: false,
  },
  {
    id: 29,
    slug: 'container-gardening-midwest-beginners',
    section: 'lifestyle',
    title: 'Container Gardening for Midwest Beginners: Start Small, Grow Something',
    byline: 'Tribune Lifestyle',
    date: 'May 5, 2026',
    category: 'Gardening',
    excerpt: 'No yard required. A Batavia master gardener breaks down everything you need to grow herbs, tomatoes, and more on a patio or balcony.',
    body: [
      'Linda Przybylski has been gardening in Kane County for 30 years, and for the past decade she has focused almost exclusively on containers. "I\'m not anti-ground gardening," she said. "But containers let you garden anywhere, control your soil completely, and move things around. For beginners, that\'s a huge advantage."',
      'Przybylski, a certified master gardener through the University of Illinois Extension, teaches container gardening workshops each spring through the Kane County Forest Preserve. Her beginner classes sell out within days of opening.',
      'Her first rule: drainage is everything. "More container plants die from overwatering than underwatering. Every pot needs drainage holes and a saucer. That\'s non-negotiable."',
      'For Midwest beginners, she recommends starting with three categories: herbs (basil, parsley, chives are nearly foolproof), cherry tomatoes (\'Sungold\' and \'Sweet 100\' varieties perform well in containers), and one pollinator flower such as zinnias or marigolds. "Those three things together will teach you everything you need to know about container growing."',
      'Soil matters more in containers than in the ground, since roots can\'t expand to find nutrients. Przybylski recommends a high-quality potting mix — not garden soil, which compacts — amended with compost and a slow-release granular fertilizer at planting time.',
      'The Fox Valley\'s last frost date is typically around May 1, which means outdoor container planting is safe now through early October. For those just starting this season, she says: "Get three pots. Plant basil. You\'ll be hooked by July."',
    ],
    tags: ['lifestyle', 'gardening', 'outdoors', 'home-design'],
    locked: false,
    featured: false,
  },
  {
    id: 30,
    slug: 'morning-routine-fox-valley-residents',
    section: 'lifestyle',
    title: 'How Fox Valley Residents Are Winning Their Mornings',
    byline: 'Tribune Lifestyle',
    date: 'May 4, 2026',
    category: 'Personal Development',
    excerpt: 'We talked to five Fox Valley residents about the morning habits that have genuinely changed their days — no 4 a.m. wakeups required.',
    body: [
      'The internet is full of extreme morning routines — cold plunges, two-hour workouts, journaling, meditation, and all of it before sunrise. Most people try them for a week and quit. A handful of Fox Valley residents have found something different: simple, sustainable habits that actually stick.',
      'Tom Kessler, a 44-year-old project manager from Aurora, starts each day by making his bed and brewing coffee before looking at his phone. That\'s the entire routine. "I spent two years trying to build elaborate mornings and failing. This one thing — not touching my phone for the first 20 minutes — changed my stress level more than anything else I\'ve tried."',
      'St. Charles high school teacher Mara Delvecchio added a 10-minute walk to her morning three years ago. "Not a workout, just a walk around the block. It creates a gap between waking up and being at school. My students notice when I\'ve done it and when I haven\'t."',
      'Batavia resident and freelance designer Chris Park swears by a written task list made the night before. "I wake up knowing exactly what the day holds. The morning calm is possible because I removed the decision-making from it."',
      'Common threads across the people we spoke with: their routines are short (20 minutes or less), they protect them actively by saying no to early meetings, and they started with one habit rather than an overhaul.',
      '"The morning routine industry wants you to think you need to transform your life," said Aurora-based therapist Dr. Priya Nair. "What the research actually shows is that one or two consistent anchors in the morning — anything that provides calm and agency — is enough to create measurable improvements in daily well-being."',
    ],
    tags: ['lifestyle', 'personal-development', 'wellness'],
    locked: true,
    featured: false,
  },
  {
    id: 31,
    slug: 'slow-living-suburbs-fox-valley',
    section: 'lifestyle',
    title: 'Unplugged in the Suburbs: Fox Valley Families Embrace Slow Living',
    byline: 'Tribune Lifestyle',
    date: 'May 3, 2026',
    category: 'Community',
    excerpt: 'A growing number of local families are deliberately stepping back from overscheduling, constant connectivity, and the pressure to optimize everything.',
    body: [
      'The Harding family of Geneva has one rule for Sunday: nothing scheduled. No sports, no birthday parties, no errands beyond what is truly urgent. They have held the rule for two years.',
      '"It was hard at first," said Sarah Harding, 41. "You feel guilty, like you\'re depriving your kids of something. But what we noticed after about three months was that our kids started to get good at being bored — and then good at entertaining themselves. That\'s a skill we\'d accidentally taken away from them."',
      'The Hardings are part of a loosely connected movement sometimes called slow living — a deliberate pushback against the over-optimization of daily life that has gained traction in suburbs like those of the Fox Valley, where families are historically among the most scheduled in the country.',
      'Its hallmarks are familiar to anyone who has felt the weight of a packed family calendar: fewer activities per child, deliberate limits on screen time, cooking from scratch more often, time outside without a destination.',
      'Geneva therapist Dr. Rachel Simms says she has seen the concept come up organically in her practice. "Families are arriving exhausted. The schedule is the presenting problem, but the underlying issue is that busyness has become a form of social currency. Saying \'we don\'t do much\' feels like a confession rather than a choice."',
      'For families curious about slowing down, the entry point need not be dramatic. The Hardings started with one protected evening per week — Tuesday dinners with no phones at the table. "That was it for six months," Sarah Harding said. "We just held that one thing. Everything else came from there."',
    ],
    tags: ['lifestyle', 'community', 'family-and-parenting', 'personal-development'],
    locked: true,
    featured: false,
  },

  {
    id: 32,
    slug: 'geneva-approves-downtown-streetscape-project-2026',
    section: 'news',
    title: 'Geneva Approves $14.2M Downtown Streetscape Overhaul Starting This Fall',
    byline: 'Maria Castillo, Tribune Staff',
    date: 'May 8, 2026',
    category: 'Local Government',
    excerpt: 'Geneva aldermen voted 8-2 to approve a major streetscape renovation along Third Street, with construction set to begin in September.',
    body: [
      'GENEVA — The Geneva City Council on Monday night approved a $14.2 million streetscape renovation project that will transform a six-block stretch of Third Street with wider sidewalks, new lighting, underground utility upgrades, and dedicated bike lanes. The 8-2 vote came after nearly three hours of public comment from business owners, residents, and downtown property managers.',
      'The project, which city officials say has been in the planning stages since 2023, will be funded through a combination of tax increment financing, a state infrastructure grant of $4.8 million secured last year, and general obligation bonds. Construction is expected to begin in mid-September and continue in phases through the spring of 2028, with crews working block by block to minimize disruption to businesses.',
      '"This is the single largest investment in our downtown core in more than 30 years," said Mayor Kevin Lindquist. "We heard the concerns about construction impacts, and we\'ve built a phasing plan that keeps every business accessible throughout the process." The city has also committed $200,000 to a merchant support fund that will provide marketing assistance and signage for shops affected by detours.',
      'Not everyone was enthusiastic. Alderman Diane Prochaska, who voted against the measure, said she worried about cost overruns and the timeline stretching into a third year. "I support modernizing Third Street, but I think we\'re taking on too much at once," Prochaska said. Several restaurant owners along the corridor echoed concerns about losing outdoor dining space during peak summer months, though city engineer Tom Hadley noted that summer 2027 work would be limited to the western blocks where fewer dining patios exist.',
      'City staff will hold two open houses later this month — May 18 at the Geneva History Museum and May 21 at the Geneva Public Library — to walk residents through construction timelines and detour maps. Detailed plans are also available on the city\'s website. The first phase will focus on underground stormwater and utility work between First and Third streets before any visible streetscape changes begin.',
    ],
    tags: ["news","government","infrastructure","business-and-finance","community"],
    locked: true,
    featured: false,
  },

  {
    id: 33,
    slug: 'batavia-girls-soccer-clinches-dupage-valley-conference-title-2026',
    section: 'sports',
    title: 'Batavia Girls Soccer Clinches DuPage Valley Conference Title With 2-1 Win',
    byline: 'Marcus Delgado, Tribune Sports',
    date: 'May 9, 2026',
    category: 'High School Sports',
    excerpt: 'Batavia defeated Geneva 2-1 on Friday night to secure an outright DuPage Valley Conference championship for the first time since 2019.',
    body: [
      'BATAVIA — Senior midfielder Ava Kowalski scored the go-ahead goal in the 67th minute Friday night as the Batavia Bulldogs defeated crosstown rival Geneva 2-1 at Bulldog Stadium, clinching an outright DuPage Valley Conference championship with a 9-0-1 league record.',
      'Kowalski, a Northern Illinois University commit, collected a through ball from junior forward Mia Trevino and slotted it past Geneva keeper Riley Sandberg to break a 1-1 deadlock that had held since halftime. The win extends Batavia\'s unbeaten streak to 14 matches and improves its overall record to 17-2-1 heading into the IHSA Class 3A postseason.',
      'Geneva struck first in the 22nd minute when sophomore Keira Lund buried a free kick from 25 yards out, but Batavia equalized just four minutes later on a header from Trevino off a corner kick delivered by Kowalski. The second half was a tightly contested affair, with Geneva goalkeeper Sandberg making five saves before Kowalski\'s decisive strike.',
      '"These girls have worked for this since last summer," Batavia head coach Jim Pawlak said after the match. "To do it against Geneva, under the lights, with the whole community watching — that\'s something they\'ll carry with them forever. Now we reset and get ready for regionals."',
      'Geneva falls to 13-5-2 overall and 6-3-1 in conference play but remains in strong position for a regional seed. The IHSA Class 3A regional pairings will be announced Monday, with first-round matches set to begin the week of May 18.',
      'Batavia will host its senior night celebration Tuesday against Naperville North before turning its full attention to the postseason. The Bulldogs were eliminated in the sectional semifinals a year ago and have not advanced past sectionals since their 2019 conference title season.',
    ],
    tags: ["sports","high-school-sports","community"],
    locked: true,
    featured: false,
  },

  {
    id: 34,
    slug: 'editorial-kane-county-warehouse-moratorium-needed',
    section: 'opinion',
    title: 'Kane County needs a warehouse moratorium before it\'s too late',
    byline: 'Tribune Staff',
    date: 'May 11, 2026',
    category: 'Editorial',
    excerpt: 'The Fox Valley Tribune editorial board urges Kane County leaders to pause industrial warehouse approvals until a comprehensive land-use plan is adopted.',
    body: [
      'The Kane County Board meets Tuesday evening to consider yet another rezoning request for speculative warehouse development, this time a 1.2-million-square-foot distribution center proposed for farmland along Fabyan Parkway west of Geneva. The board should reject the proposal and, more importantly, impose an immediate moratorium on new warehouse approvals until the county adopts a comprehensive logistics corridor plan that protects residents, preserves agriculture, and accounts for infrastructure costs.',
      'Over the past three years, more than 4.5 million square feet of warehouse and logistics space has been approved or constructed in unincorporated Kane County, much of it on prime agricultural land that will never be farmed again. Residents in Campton Hills, rural Elburn, and the Kaneville area have packed hearing after hearing to voice concerns about truck traffic on two-lane roads, diesel emissions near schools, and stormwater runoff into tributaries of the Fox River. Their objections have largely been noted and then ignored.',
      'Proponents argue that warehouse development broadens the tax base and creates jobs. Those claims deserve scrutiny. A 2024 analysis by the Kane County Division of Transportation estimated that a single large distribution center generates between 800 and 1,400 daily truck trips, accelerating road deterioration that county taxpayers ultimately pay to repair. The jobs created are often part-time, offer limited benefits, and pay wages that do little to offset the rising cost of living in the Fox Valley. Meanwhile, the lost farmland represents an irreversible choice made on behalf of future generations.',
      'We are not opposed to economic development, nor do we suggest that logistics facilities have no place in Kane County. But responsible planning requires that infrastructure capacity, environmental impact, and community character be evaluated holistically before individual projects are rubber-stamped parcel by parcel. A six-month moratorium would give the county time to complete its long-delayed land-use framework, engage residents meaningfully, and establish clear standards for setbacks, traffic mitigation, and stormwater management.',
      'Board members who face voters next spring should ask themselves a straightforward question: Will the residents of Kane County in 2036 thank us for trading fertile prairie soil and open horizons for a corridor of concrete and diesel fumes? If the answer gives them pause, they should vote accordingly on Tuesday night.',
    ],
    tags: ["opinion","local-politics","government","environment","infrastructure"],
    locked: true,
    featured: false,
  },

  {
    id: 35,
    slug: 'aurora-city-council-approves-affordable-housing-overlay-district',
    section: 'local-politics',
    title: 'Aurora City Council Approves Affordable Housing Overlay for East Side',
    byline: 'Marcus Delgado, Tribune Staff',
    date: 'May 11, 2026',
    category: 'Local Politics',
    excerpt: 'Aurora aldermen voted 8-4 Monday to create a new affordable housing overlay district along East New York Street corridor.',
    body: [
      'AURORA — The Aurora City Council voted 8-4 Monday night to approve an affordable housing overlay district spanning a 14-block stretch of the East New York Street corridor, a move supporters say will spur development of mixed-income housing in one of the city\'s most underserved neighborhoods.',
      'The overlay, which takes effect July 1, will require developers building projects of 20 or more units within the district to set aside at least 15 percent of units as affordable, defined as accessible to households earning 60 percent or less of the area median income. In exchange, developers will receive density bonuses allowing up to two additional stories beyond current zoning limits and expedited permitting through the city\'s planning department.',
      'Alderman Patricia Okonkwo of the 5th Ward, who introduced the measure in February, said the vote represents years of community advocacy. "Families in this neighborhood have waited a long time for the city to back up its equity commitments with real policy," Okonkwo said after the vote. "This is a tool that says growth here must include the people who already call it home."',
      'Opponents, including Alderman Kevin Streich of the 9th Ward, argued the mandate could discourage private investment in a corridor that has struggled to attract developers. "We are adding costs and complexity at exactly the wrong time, when construction financing is already tight," Streich said during floor debate. The Illinois Realtors Association\'s Kane County chapter submitted written opposition ahead of the meeting, calling the overlay a de facto rent control mechanism.',
      'City planning director Angela Ruiz told the council that her office has already fielded inquiries from three development groups interested in projects within the overlay boundaries, including a proposed 72-unit building at the former Copley Hospital parking site on South Lincoln Avenue. The council\'s housing committee will review implementation guidelines at its June 2 meeting.',
      'Monday\'s vote comes as several Fox Valley municipalities, including Elgin and North Aurora, weigh their own inclusionary housing policies amid rising rents across Kane County. According to data from the Kane County Housing Authority, average rents in Aurora rose 11 percent over the past two years, outpacing wage growth in the region.',
    ],
    tags: ["local-politics","government","community","infrastructure"],
    locked: true,
    featured: false,
  },

  {
    id: 36,
    slug: 'fox-valley-families-embrace-container-gardening-small-spaces-2026',
    section: 'lifestyle',
    title: 'Fox Valley Families Turn to Container Gardening as Patio Season Arrives',
    byline: 'Tribune Lifestyle',
    date: 'May 11, 2026',
    category: 'Home & Garden',
    excerpt: 'Local nurseries report a surge in container gardening supplies as suburban families maximize patios, balconies, and small yards this spring.',
    body: [
      'As temperatures finally settled into the mid-60s across the Fox Valley this past week, families from Batavia to St. Charles have been flooding local garden centers in search of compact planters, dwarf vegetable varieties, and self-watering containers that promise fresh herbs and tomatoes without a sprawling backyard plot.',
      'At Prairie Path Nursery in Geneva, owner Linda Sorensen said sales of fabric grow bags and tiered planter systems are up nearly 40 percent compared to this time last year. "We\'re seeing a lot of younger families, couples in townhomes, even apartment renters who want to grow their own food but only have a six-by-eight patio to work with," Sorensen said. "The interest in growing something edible at home hasn\'t slowed down since the pandemic years — it\'s just gotten more creative."',
      'Container gardening offers several advantages for Fox Valley residents navigating the region\'s notoriously unpredictable spring weather. Pots and raised planters warm faster than ground soil, giving growers a head start after late frosts. They also allow families to move tender plants like basil and peppers indoors on chilly nights, a practical consideration given that Kane and DuPage counties can still see overnight lows in the upper 30s through mid-May.',
      'Rebecca Muller, a University of Illinois Extension master gardener who leads workshops at the Batavia Public Library, recommends starting with cherry tomatoes, lettuce, and culinary herbs for beginners. "A single 18-inch pot with a cherry tomato plant, some trailing thyme, and a marigold for pollinator attraction can produce food all summer and looks beautiful on a front step," Muller said. She noted that the Extension office\'s next free container gardening workshop is scheduled for Saturday, May 16, at the St. Charles Public Library.',
      'For families looking to involve children, Sorensen suggests snap peas and radishes, which germinate quickly and give young gardeners visible results within days. Several Fox Valley park districts, including those in Aurora and North Aurora, have also added community container garden plots to their summer programming this year, offering an entry point for residents without any outdoor space of their own.',
      'With Memorial Day weekend approaching and most frost risk behind the region, garden center staff say the next two weeks represent the ideal window for Fox Valley residents to get containers planted and established before the heat of June arrives.',
    ],
    tags: ["lifestyle","home-design","outdoors","family-and-parenting","community","food-and-drink"],
    locked: true,
    featured: false,
  },

  {
    id: 37,
    slug: 'geneva-approves-downtown-streetscape-project-2026-1778549882144',
    section: 'news',
    title: 'Geneva Aldermen Approve $14.2M Downtown Streetscape Overhaul',
    byline: 'Marcus Callahan',
    date: 'May 11, 2026',
    category: 'Local Government',
    excerpt: 'Geneva\'s City Council voted 7-3 Monday night to fund a major redesign of Third Street, adding wider sidewalks and new infrastructure.',
    body: [
      'GENEVA — The Geneva City Council on Monday approved a $14.2 million streetscape improvement project that will reshape a six-block stretch of Third Street through the heart of the downtown historic district, adding wider sidewalks, buried utility lines, and dedicated bicycle infrastructure.',
      'The 7-3 vote followed nearly two hours of public comment from residents and business owners split between enthusiasm for modernization and concern over construction disruptions during the busy summer tourism season. Alderman Janet Kovacic, who chairs the Public Works Committee, said the project had been studied for more than three years and delayed twice due to pandemic-era cost inflation.',
      '"This is the single largest investment in our downtown in a generation," Kovacic told the packed council chambers. "We owe it to the next 50 years of Geneva residents to get this right, and we believe this plan does that." Construction is expected to begin in September and proceed in three phases through late 2027.',
      'Under the plan, Third Street between State Street and South Street will receive new sandstone-colored pavers, LED streetlights styled to match the district\'s historic character, widened sidewalks on both sides, and a protected bike lane on the eastbound corridor. Underground stormwater detention basins are also included to address recurring flooding near the Kane County Courthouse.',
      'The city will fund the project through a combination of existing capital reserves, a low-interest Illinois Environmental Protection Agency loan for the stormwater components, and tax-increment financing revenue from the downtown TIF district. Alderman Robert Fenn, who voted against the measure, argued the timeline was too aggressive and called for a phased funding approach that would reduce borrowing costs.',
      'City Manager Stephanie Dawkins said a detailed construction phasing schedule and business mitigation plan would be presented at the June 8 council meeting, and that a dedicated hotline and weekly email updates would keep merchants informed of lane closures and detour routes throughout the project.',
    ],
    tags: ["news","government","infrastructure","community"],
    locked: true,
    featured: false,
  },
];
