export const COLORS = {
  primary: '#C41230',
  dark: '#1A1A1A',
  sectionNews: '#0D3B6E',
  sectionSports: '#1B5E20',
  sectionOpinion: '#4A148C',
  gray: '#666666',
  lightGray: '#F7F7F7',
  border: '#E0E0E0',
};

export const SECTION_COLORS = {
  news: COLORS.sectionNews,
  sports: COLORS.sectionSports,
  opinion: COLORS.sectionOpinion,
};

export const PIANO_CONFIG = {
  AID: 'QiNgMM49pu',
  OFFER_ID: 'OFSKQS2JDQIS',
  SUBSCRIBER_RESOURCE_ID: null, // Set to your subscriber resource ID: "RXXXXXXXX"
};

export const ARTICLES = [
  // ── NEWS ──────────────────────────────────────────────────────────────────
  {
    id: 1,
    slug: 'county-board-approves-road-repair-budget',
    section: 'news',
    title: 'County Board Approves $2.3M Road Repair Budget for 2026',
    byline: 'Tribune Staff',
    date: 'April 28, 2026',
    category: 'Government',
    excerpt: 'The Kane County Board voted 18-3 Tuesday to approve a $2.3 million road repair budget for the 2026 fiscal year, prioritizing 14 miles of deteriorating county roads that officials say have reached the end of their useful life. The measure allocates $1.4 million for resurfacing projects in the eastern district and $900,000 for drainage improvements on Route 47 north of Huntley. Work is expected to begin in late May and wrap up before first frost. Three board members voted against the measure, calling for more competitive contract solicitation before approving the spending.',
    body: [
      'The Kane County Board voted 18-3 Tuesday to approve a $2.3 million road repair budget for the 2026 fiscal year, prioritizing 14 miles of deteriorating county roads that officials say have reached the end of their useful life.',
      'The measure, which passed after three weeks of public comment, allocates $1.4 million for resurfacing projects on rural county roads in the eastern district and $900,000 for drainage improvements on Route 47 north of Huntley.',
      '"These roads have been on our radar for five years," said County Engineer Patricia Hollis. "We\'ve done everything we can to extend their life with patch repairs, but we\'ve reached the point where we need to invest properly."',
      'The funding comes from a combination of state transportation grants and county motor fuel tax revenues. Work is expected to begin in late May and wrap up before first frost.',
      'Three board members voted against the measure, citing concerns about the bidding process and calling for more competitive contract solicitation. Board member David Kirchoff said he would request an audit of project procurement once work begins.',
    ],
    locked: true,
    featured: true,
  },
  {
    id: 2,
    slug: 'new-grocery-store-downtown-geneva',
    section: 'news',
    title: 'New Full-Service Grocery Store Planned for Downtown Geneva',
    byline: 'Tribune Staff',
    date: 'April 27, 2026',
    category: 'Business',
    excerpt: 'A Chicago-based grocery chain announced plans to open a 28,000-square-foot store in the former Sears building on State Street, filling a retail gap residents have complained about for years.',
    body: [
      'A Chicago-based grocery chain announced plans Monday to open a 28,000-square-foot store in the former Sears building on State Street, ending a three-year search by city planners for an anchor tenant.',
      'Fresh Thyme Market, which operates 24 stores in the Midwest, signed a 15-year lease and expects to open by March 2027 pending city approvals.',
      '"This is exactly the kind of tenant we\'ve been working to attract," said Geneva City Manager Rob Godskesen. "Having a full-service grocery downtown will change the dynamic for residents who currently have to drive out to the suburbs for basics."',
      'The store will employ approximately 85 full- and part-time workers and generate an estimated $180,000 in annual sales tax revenue for the city.',
    ],
    locked: false,
    featured: false,
  },
  {
    id: 3,
    slug: 'school-district-teacher-shortage',
    section: 'news',
    title: 'School District Faces Growing Teacher Shortage Ahead of Fall',
    byline: 'Education Reporter',
    date: 'April 26, 2026',
    category: 'Education',
    excerpt: 'With 34 open teaching positions and hiring season underway, District 303 officials are weighing emergency certification programs and increased pay for hard-to-fill roles.',
    body: [
      'With 34 open teaching positions and the prime hiring season half over, School District 303 is facing its most acute staffing shortage in more than a decade, officials acknowledged at Monday\'s board meeting.',
      'The vacancies span nearly every subject area but are most concentrated in special education, high school math, and elementary bilingual classrooms — roles that have proven increasingly difficult to fill across Illinois.',
      '"We\'re competing with every district in the region for the same pool of candidates," said Human Resources Director Tanya Ostrander. "The pipeline from teacher preparation programs simply hasn\'t kept pace with demand."',
      'The board voted to authorize emergency hiring measures including signing bonuses of up to $5,000 for high-need positions and a new partnership with Northern Illinois University to bring student teachers into classrooms starting this fall.',
      'Officials also said they are exploring a grow-your-own pipeline program that would offer tuition assistance to paraprofessionals already working in the district who want to pursue teaching certification.',
    ],
    locked: true,
    featured: false,
  },
  {
    id: 4,
    slug: 'water-main-break-route-31',
    section: 'news',
    title: 'Water Main Break Closes Lanes on Route 31 Near Elgin',
    byline: 'Tribune Staff',
    date: 'April 25, 2026',
    category: 'Local',
    excerpt: 'A 12-inch water main ruptured Tuesday morning, closing two northbound lanes and cutting service to approximately 800 customers in the surrounding area.',
    body: [
      'A 12-inch water main ruptured early Tuesday morning near the intersection of Route 31 and Bowes Road, closing two northbound lanes and cutting water service to approximately 800 customers in the surrounding neighborhood.',
      'Crews from the Fox Valley Water Authority responded at 4:42 a.m. and worked through the afternoon to isolate the break and restore pressure to affected addresses.',
      'Service was fully restored by 6:30 p.m. Northbound lanes on Route 31 remained partially closed through Wednesday morning while crews completed pavement repairs.',
      'The main, installed in 1987, had been flagged in the authority\'s infrastructure assessment as nearing the end of its expected service life. Officials said a replacement project for this segment was already in the capital plan for 2027.',
    ],
    locked: false,
    featured: false,
  },

  // ── SPORTS ────────────────────────────────────────────────────────────────
  {
    id: 5,
    slug: 'batavia-bulldogs-regional-championship',
    section: 'sports',
    title: 'Batavia Bulldogs Capture Regional Title in Overtime Thriller',
    byline: 'Tribune Sports',
    date: 'April 28, 2026',
    category: 'High School Soccer',
    excerpt: 'Senior midfielder Connor Walsh scored in the 94th minute to lift Batavia past St. Charles East 2-1 in a regional boys soccer final that kept the home crowd on its feet throughout.',
    body: [
      'Senior midfielder Connor Walsh scored in the 94th minute to lift the Batavia Bulldogs past St. Charles East 2-1 in a regional boys soccer final Saturday that had the home crowd on its feet throughout.',
      'Walsh collected a through ball from sophomore Mateo Hernandez and beat the keeper low to the left post, setting off a celebration that spilled onto the field.',
      '"I was just trying to stay patient and wait for my moment," Walsh said afterward. "Mateo found me perfectly. I knew exactly what I wanted to do."',
      'The Bulldogs, now 16-4-2, advance to the sectional semifinals Wednesday against Wheaton Warrenville South. It will be Batavia\'s fourth sectional appearance in six years.',
      'St. Charles East had taken the lead at 62 minutes on a free kick from Damian Torres before Batavia equalized on a penalty by junior Kyle Peterson at 71 minutes.',
    ],
    locked: true,
    featured: true,
  },
  {
    id: 6,
    slug: 'st-charles-north-wrestler-state-title',
    section: 'sports',
    title: 'St. Charles North Senior Wins State Wrestling Title at 170 Pounds',
    byline: 'Tribune Sports',
    date: 'April 26, 2026',
    category: 'High School Wrestling',
    excerpt: 'Marcus Webb pinned his opponent in 1:47 of the championship match to give St. Charles North its first individual state wrestling title since 2019.',
    body: [
      'Marcus Webb pinned his Springfield Southeast opponent in 1:47 of the championship match Saturday to give St. Charles North its first individual state title in wrestling since 2019.',
      'Webb, a three-time state qualifier who finished third a year ago, was dominant throughout the tournament, allowing just five points across five matches.',
      '"This is what I\'ve worked for since I was a freshman," said Webb, who finished the season 41-1. "Every early morning, every extra session — it was all worth it today."',
      'Webb committed to the University of Illinois in February, where he will compete beginning next fall.',
      'St. Charles North coach Rick Pirrello called Webb "the most technically sound wrestler we\'ve coached in 20 years." The team finished 12th in the team standings — its best result since 2018.',
    ],
    locked: true,
    featured: false,
  },
  {
    id: 7,
    slug: 'youth-soccer-league-expansion',
    section: 'sports',
    title: 'Fox Valley Youth Soccer League Expanding to Three New Communities',
    byline: 'Tribune Staff',
    date: 'April 24, 2026',
    category: 'Youth Sports',
    excerpt: 'The Fox Valley Youth Soccer League will add divisions in Carpentersville, Burlington, and Sleepy Hollow starting with the fall 2026 season.',
    body: [
      'The Fox Valley Youth Soccer League announced Thursday it will expand into three new communities — Carpentersville, Burlington, and Sleepy Hollow — beginning with the fall 2026 season.',
      'The expansion adds approximately 340 players and nine new teams to a league that currently serves more than 2,400 youth athletes across 18 communities.',
      '"The demand in these communities has been there for years," said league director Angela Moreno. "We finally have the volunteer base and field agreements in place to serve those kids well."',
      'Registration for fall leagues opens May 15 at foxvalleysoccer.org.',
    ],
    locked: false,
    featured: false,
  },

  // ── OPINION ───────────────────────────────────────────────────────────────
  {
    id: 8,
    slug: 'editorial-infrastructure-investment',
    section: 'opinion',
    title: 'Editorial: The Time to Fix Our Roads Is Now',
    byline: 'Tribune Editorial Board',
    date: 'April 28, 2026',
    category: 'Editorial',
    excerpt: "The county board's road repair vote is welcome — but it's a down payment on years of deferred maintenance that has cost taxpayers far more in the long run.",
    body: [
      "Tuesday's county board vote approving $2.3 million for road repairs is welcome news for drivers who have navigated the same crumbling county roads for the better part of a decade. But let's be clear: it's a down payment, not a solution.",
      "Kane County's infrastructure maintenance backlog now exceeds $47 million by the administration's own estimate. At Tuesday's funding level, it would take more than 20 years to work through it — assuming no new roads deteriorate in the meantime.",
      'The hard truth is that years of kicking the can down the road has cost taxpayers more, not less. Pavement that costs $3 per square foot to maintain today costs $12 to reconstruct once it fails completely.',
      'We commend the board majority for acting. Now they need to follow this vote with a long-term infrastructure plan that honestly addresses the backlog and builds in sustainable annual investment — before the next round of patches becomes the next round of full reconstruction.',
    ],
    locked: true,
    featured: false,
  },
  {
    id: 9,
    slug: 'letter-support-local-businesses',
    section: 'opinion',
    title: 'Letter: Support Local Businesses — They Support Us',
    byline: 'Margaret Holbrook, St. Charles',
    date: 'April 26, 2026',
    category: 'Letter to the Editor',
    excerpt: 'As the downtown shopping season picks up, I want to remind neighbors that every dollar spent locally stays in our community in ways that big-box and online spending simply cannot match.',
    body: [
      'As spring arrives and the downtown shopping season picks up, I want to remind my neighbors of something easy to forget in a world of one-click ordering: local businesses are the backbone of what makes Fox Valley worth living in.',
      "When you buy from a shop on State Street or Third Street, that owner is the person who sponsors your kid's Little League team, buys an ad in the school musical program, and shows up at city hall to fight for a stoplight at a dangerous intersection.",
      "Amazon doesn't do that. Walmart doesn't do that.",
      "I'm not asking anyone to pay twice as much or go without. I'm asking us to think before defaulting to the easiest option. Give the local place a shot first.",
      '— Margaret Holbrook, St. Charles',
    ],
    locked: false,
    featured: false,
  },
  {
    id: 10,
    slug: 'commentary-election-results-fox-valley',
    section: 'opinion',
    title: 'Commentary: What April\'s Results Mean for Fox Valley\'s Political Future',
    byline: 'James Kearney, Political Analyst',
    date: 'April 25, 2026',
    category: 'Commentary',
    excerpt: "Shifting margins in suburban precincts signal a realignment that neither party has fully grasped — and the 2028 cycle may be decided in places that weren't even competitive two years ago.",
    body: [
      "The numbers from Tuesday's consolidated election are in, and if you know where to look, they tell a story that goes well beyond who won and lost.",
      'In three Kane County precincts that voted reliably Republican as recently as 2020, margins have shrunk to single digits. In two Kendall County townships that were toss-ups in 2022, Democrats now hold double-digit leads. The suburbs are still moving.',
      "What's driving it? Partly demographics: younger, more educated families have continued to move into the Fox Valley corridor, and they vote differently than the retirees and longtime residents who defined these communities politically for 30 years.",
      "But it's also about local issues. Voters I spoke with mentioned school board controversies, water quality concerns, and — yes — road conditions. The infrastructure vote that led today's Tribune is directly connected to the political anxieties playing out in these margins.",
      'Candidates who want to win here in 2028 would do well to pay attention.',
    ],
    locked: true,
    featured: false,
  },
];
